Text_SwordsDanceTeach::
    .string "Y'a pas beaucoup de monde qui\n"
    .string "passe dans le coin.\p"
    .string "Si je m'entraîne là, je deviendrai\n"
    .string "de plus en plus fort, c'est sûr!\p"
    .string "Ouais, de plus en plus fort…\p"
    .string "Ça te dirait d'apprendre cette\n"
    .string "capacité? C'est DANSE-LAMES.$"

Text_SwordsDanceDeclined::
    .string Ben, tant pis.$"

Text_SwordsDanceWhichMon::
    .string "Cool, choisis le POKéMON qui\n"
    .string "doit l'apprendre.$"

Text_SwordsDanceReteach::
    .string "J'essaye de devenir de plus\n"
    .string "en plus fort…\p"
    .string "J'ai entendu que des objets pour\n"
    .string "renforcer les POKéMON existent mais\p"
    .string "ils sont très cher!\p"
    .string "Donc maintenant je fais payer\n"
    .string "¥5000 pour apprendre DANSE-LAMES.$"

Text_SwordsDanceReteach2::
    .string "Tu veux apprendre DANSE-LAMES à\n"
    .string "un de tes POKéMON?$"

Text_SwordsDanceNotEnoughMoney::
    .string "Tu n'as pas ¥5000?\p"
    .string "Je suis désolé mais j'ai besoin\n"
    .string "d'argent pour améliorer mes POKéMON.\p"
    .string "Je t'apprendrais DANSE-LAMES quand\n"
    .string "tu auras assez d'argent.$"

Text_SwordsDanceTaught::
    .string "Si seulement on pouvait toujours\n"
    .string "progresser, ça serait mortel!$"

SevenIsland_Text_IslandSign::
    .string "ILE 7\n"
    .string "L'île de l'infinité$"

SevenIsland_Text_IslandsMadeInSevenDays::
    .string "On appelle ces 7 îles les ILES\n"
    .string "SEVII, mais je sais pas pourquoi.\p"
    .string "… En tout cas c'est plein\n"
    .string "de jeunes ici.\p"
    .string "A ce qu'on raconte, elles auraient\n"
    .string "été créées en 7 jours.$"

SevenIsland_Text_IslandVirtuallyUntouched::
    .string "Ces îles ont été conservées dans\n"
    .string "leur état naturel.\p"
    .string "Ça rend les excursions un peu\n"
    .string "plus difficiles que la normale.$"

SevenIsland_Text_FadedWriting::
    .string "Le texte s'est effacé avec le temps…$"

SevenIsland_Text_BattleHouseWithNoVisitors::
    .string "MAISON DE COMBAT\n"
    .string "…Il n'y a personne d'inscrit.$"

SevenIsland_Text_BattleHouseOneVisitor::
    .string "MAISON DE COMBAT\n"
    .string "Il y a une personne d'inscrite:\p"
    .string "{STR_VAR_1}.$"

SevenIsland_Text_BattleHouseTwoVisitors::
    .string "MAISON DE COMBAT\n"
    .string "Il y a deux personnes d'inscrites:\p"
    .string "{STR_VAR_1}.$"

SevenIsland_Text_BattleHouseThreeVisitors::
    .string "MAISON DE COMBAT\n"
    .string "Il y a trois personnes d'inscrites:\p"
    .string "{STR_VAR_1}.$"

SevenIsland_Text_BattleHouseFourVisitors::
    .string "MAISON DE COMBAT\n"
    .string "Il y a quatre personnes d'inscrites:\p"
    .string "{STR_VAR_1}.$"

SevenIsland_Text_BattleHouseFiveVisitors::
    .string "MAISON DE COMBAT\n"
    .string "Il y a cinq personnes d'inscrites:\p"
    .string "{STR_VAR_1}.$"

SevenIsland_Text_BattleHouseSixVisitors::
    .string "MAISON DE COMBAT\n"
    .string "Il y a six personnes d'inscrites:\p"
    .string "{STR_VAR_1}.$"

SevenIsland_Text_BattleHouseSevenVisitors::
    .string "MAISON DE COMBAT\n"
    .string "Il y a sept personnes d'inscrites:\p"
    .string "{STR_VAR_1}.$"
