OneIsland_PokemonCenter_1F_Text_BillHeyThereCelio::
    .string "LEO: Salut CILEO!$"

OneIsland_PokemonCenter_1F_Text_CelioCantBelieveYouCameOut::
    .string "CILEO: LEO!\p"
    .string "J'arrive pas à croire que tu\n"
    .string "sois venu.$"

OneIsland_PokemonCenter_1F_Text_BillHowsYourResearchComing::
    .string "LEO: Eh bien oui, je suis là.\p"
    .string "ALors, comment avancent tes\n"
    .string "recherches?\p"
    .string "… Oh, une seconde!$"

OneIsland_PokemonCenter_1F_Text_ThisIsMyBuddyCelio::
    .string "Il faut que je vous présente.\n"
    .string "{PLAYER}, voilà mon ami CILEO.\p"
    .string "C'est un fou d'informatique.$"

OneIsland_PokemonCenter_1F_Text_PlayerIsRisingPokemonChamp::
    .string "CILEO, je te présente {PLAYER}.$"

OneIsland_PokemonCenter_1F_Text_PlayerIsReigningPokemonChamp::
    .string "CILEO, je te présente {PLAYER}.\p"
    .string "{PLAYER} sera très bientôt un grand\n"
    .string "CHAMPION, j'en suis sûr!$"

OneIsland_PokemonCenter_1F_Text_CelioThatsReallyImpressive::
    .string "CILEO: Impressionnant.\p"
    .string "Je dois bien avouer que je ne\n"
    .string "suis pas doué pour le combat.\p"
    .string "En tout cas, je suis ravi de te\n"
    .string "rencontrer.$"

OneIsland_PokemonCenter_1F_Text_BillBringMeUpToSpeed::
    .string "LEO: Bon, dis-moi tout.\n"
    .string "Comment fonctionne ta machine?$"

OneIsland_PokemonCenter_1F_Text_CelioPCsCantLinkWithYours::
    .string "CILEO: Plutôt pas mal.\p"
    .string "Mais le problème c'est que nous\p"
    .string "sommes éloignés de tout ici.\n"
    .string "Et le PC ne peut pas se connecter\n"
    .strign "au tien, LEO.$"

OneIsland_PokemonCenter_1F_Text_BillLetMeHelpYou::
    .string "LEO: Ah oui?\n"
    .string "Laisse-moi jeter un œil.\p"
    .string "… Hum…\n"
    .string "Je crois que ça peut s'arranger.\l"
    .string "Tu veux bien que je t'aide?$"

OneIsland_PokemonCenter_1F_Text_CanYouDeliverThisMeteoritePlayer::
    .string "{PLAYER}, est-ce que je peux te\n"
    .string "demander d'attendre un peu?\p"
    .string "En fait, j'ai même un service à\n"
    .string "te demander.\p"
    .string "L'île voisine s'appelle l'ILE 2.\p"
    .string "Il y a un type qui dirige la\n"
    .string "SALLE DE JEU, c'est un\p"
    .string "passionné de pierres précieuses\n"
    .string "et de roches rares.\p"
    .string "Est-ce que tu pourrais lui\n"
    .string "apporter ce METEORITE?$"

OneIsland_PokemonCenter_1F_Text_AcceptedMeteoriteFromBill::
    .string "{PLAYER} accepte la METEORITE\n"
    .string "de LEO.$"

OneIsland_PokemonCenter_1F_Text_CelioPleaseTakeThis::
    .string "CILEO: {PLAYER}, si tu vas sur\n"
    .string "l'ILE 2, prends ça avec toi.$"

OneIsland_PokemonCenter_1F_Text_PassLetsYouTravelBetweenIslands::
    .string "C'est un PASSE pour le ferry\n"
    .string "reliant les îles entre elles.\p"
    .string "Avec ça, tu pourras aller sur les\n"
    .string "ILES 1, 2 et 3.\p"
    .string "Oh, il faudrait aussi que tu\n"
    .string "prennes ça.$"

OneIsland_PokemonCenter_1F_Text_ReceivedExtraPageForTownMap::
    .string "{PLAYER} obtient des nouvelles page\n"
    .string "pour la CARTE!$"

OneIsland_PokemonCenter_1F_Text_ReceivedTownMap::
    .string "{PLAYER} obtient la\n"
    .string "CARTE!$"

OneIsland_PokemonCenter_1F_Text_BillCatchYouLater::
    .string "LEO: On se revoit plus tard.\p"
    .string "Dis bonjour au type de la SALLE\n"
    .string "DE JEU pour moi.$"

OneIsland_PokemonCenter_1F_Text_HmmHowAboutLikeThis::
    .string "Hum…\p"
    .string "Et si on essayait comme ça!…$"

OneIsland_PokemonCenter_1F_Text_GotPCWorkingStrollAWhileMore::
    .string "Oh, hey, {PLAYER}!\p"
    .string "Did you see?\n"
    .string "We got the PC working!\p"
    .string "I've got a few things to show\n"
    .string "CELIO here.\p"
    .string "Can you go out on a stroll or\n"
    .string "something for a while more?$"

OneIsland_PokemonCenter_1F_Text_SorryForBeingPoorHost::
    .string "I'm sorry for taking up so much of\n"
    .string "BILL's time.\p"
    .string "I'm also sorry for being such a \n"
    .string "poor host on your visit here.$"

OneIsland_PokemonCenter_1F_Text_UsualPCServicesUnavailable::
    .string "The usual PC services aren't\n"
    .string "available…$"

OneIsland_PokemonCenter_1F_Text_BillOhHeyPlayer::
    .string "LEO: Oh!\p"
    .string "{PLAYER}!\n"

OneIsland_PokemonCenter_1F_Text_BillWeGotItDone::
    .string "LEO: Qu'est-ce qui t'a retenu\n"
    .string "comme ça?\p"
    .string "Nous, on a terminé! Les PC\n"
    .string "fonctionnent à merveille.$"

OneIsland_PokemonCenter_1F_Text_CelioJobWentQuick::
    .string "CILEO: LEO est un vrai pro.\p"
    .string "Il a réussi à tout mettre en ligne\n"
    .string "en un rien de temps.$"

OneIsland_PokemonCenter_1F_Text_BillYouveLearnedALot::
    .string "LEO: Non, non.\n"
    .string "C'était vraiment rien.\p"
    .string "Tout ça c'est grâce à toi CILEO,\n"
    .string "j'aurais rien pu faire seul.$"

OneIsland_PokemonCenter_1F_Text_CelioOhReallyEhehe::
    .string "CILEO: Oh?\n"
    .string "Merci…$"

OneIsland_PokemonCenter_1F_Text_BillWeShouldHeadBackToKanto::
    .string "LEO: Bon, maintenant que tout\n"
    .string "fonctionne, on peut repartir\p"
    .string "pour KANTO.\n"
    .string "A bientôt CILEO.$"

OneIsland_PokemonCenter_1F_Text_CelioPromiseIllShowYouAroundSometime::
    .string "CILEO: {PLAYER}, je suis vraiment\n"
    .string "désolé d'avoir passé tout ce\p"
    .string "temps sur le PC.\p"
    .string "C'est promis, la prochaine fois,\n"
    .string "je te ferai visiter les îles.$"

OneIsland_PokemonCenter_1F_Text_CelioImModifyingMyNetworkMachine::
    .string "CELIO: Hello!\n"
    .string "You look awfully busy as always.\p"
    .string "How am I doing?\p"
    .string "Well, I'm modifying my Network\n"
    .string "Machine.\p"
    .string "When I get done with the machine,\n"
    .string "I hope you'll be first to use it,\l"
    .string "{PLAYER}.$"

OneIsland_PokemonCenter_1F_Text_CelioCaughtMoreMonMaybeICanBeUseful::
    .string "CELIO: {PLAYER}, how have things\n"
    .string "been for you?\p"
    .string "Oh, is that right?\n"
    .string "You've caught more POKéMON.\p"
    .string "Do you know what?\n"
    .string "Maybe I can be useful to you.$"

OneIsland_PokemonCenter_1F_Text_YoullBeTradingFromTrainersFarAway::
    .string "I'm modifying the Network Machine\n"
    .string "right now.\p"
    .string "I'm changing it so it can handle\n"
    .string "trades over long distances.\p"
    .string "When I get finished, you'll be\n"
    .string "trading for exotic POKéMON from\l"
    .string "TRAINERS far away.$"

OneIsland_PokemonCenter_1F_Text_NeedsSpecialGemstone::
    .string "But, there is a slight catch.\p"
    .string "For the link to work, the Machine\n"
    .string "needs a special gemstone.\p"
    .string "It's supposed to be on ONE ISLAND,\n"
    .string "but I haven't found one yet.\p"
    .string "Who knows where it could be.$"

OneIsland_PokemonCenter_1F_Text_TryingToFindGem::
    .string "I was trying to find the gem\n"
    .string "even while I was studying.\p"
    .string "As a result, I've made no headway\n"
    .string "in both my search and studies…\p"
    .string "If I relied on BILL, I'm sure my\n"
    .string "research would progress.\p"
    .string "But this time, I want to try to do\n"
    .string "things by myself.$"

OneIsland_PokemonCenter_1F_Text_OhThats::
    .string "Oh!\n"
    .string "Th-that's…$"

OneIsland_PokemonCenter_1F_Text_HandedRubyToCelio::
    .string "{PLAYER} handed the RUBY\n"
    .string "to CELIO.$"

OneIsland_PokemonCenter_1F_Text_MayIAskOneMoreFavor::
    .string "Thank you!\n"
    .string "{PLAYER}, you're simply amazing.\p"
    .string "… … …  … … …\p"
    .string "Um… May I ask one more giant favor\n"
    .string "of you?$"

OneIsland_PokemonCenter_1F_Text_PleaseINeedYourHelp::
    .string "It… It's not anything weird.\n"
    .string "Please, I need your help.$"

OneIsland_PokemonCenter_1F_Text_AnotherGemstoneInSeviiIslands::
    .string "While I was studying gemstones,\n"
    .string "I discovered something important.\p"
    .string "There is another gem that forms\n"
    .string "a pair with this RUBY.\p"
    .string "That other gemstone is supposed to\n"
    .string "be in the SEVII ISLANDS.\p"
    .string "{PLAYER}, please, I need you to go\n"
    .string "find the other gem.\p"
    .string "{PLAYER}, may I have your ferry\n"
    .string "PASS and the TOWN MAP?$"

OneIsland_PokemonCenter_1F_Text_ReturnedTriPassForRainbowPass::
    .string "{PLAYER} returned the TRI-PASS and\n"
    .string "received the RAINBOW PASS.$"

OneIsland_PokemonCenter_1F_Text_ObtainedExtraMapPage::
    .string "Obtained an extra page for the\n"
    .string "TOWN MAP!$"

OneIsland_PokemonCenter_1F_Text_PassLetYouGetToAllIslands::
    .string "This is my own ferry PASS.\p"
    .string "It will let you get to all the\n"
    .string "SEVII ISLANDS.\p"
    .string "{PLAYER}, please, I can't do\n"
    .string "it without your help.$"

OneIsland_PokemonCenter_1F_Text_PassLetYouGetToAllIslandsScott::
    .string "This is my own ferry PASS.\p"
    .string "It will let you get to all the\n"
    .string "SEVII ISLANDS.\p"
    .string "{PLAYER}, please, I can't do\n"
    .string "it without your help.\p"
    .string "As the CHAMPION, your POKéMON\n"
    .string "are amazingly strong.\p"
    .string "You should be safe exploring\n"
    .string "the rest of the islands.$"

OneIsland_PokemonCenter_1F_Text_HandedSapphireToCelio::
    .string "{PLAYER} handed the SAPPHIRE\n"
    .string "to CELIO.$"

OneIsland_PokemonCenter_1F_Text_ThankYouGiveMeTime::
    .string "CELIO: So this is the gem that\n"
    .string "forms a pair with the RUBY…\p"
    .string "{PLAYER}, you've gone through a lot\n"
    .string "to get this, didn't you?\p"
    .string "You don't have to tell me. I know\n"
    .string "it wasn't easy.\p"
    .string "Thank you so much!\p"
    .string "Now it's my turn to work for you!\n"
    .string "Please give me a little time.$"

OneIsland_PokemonCenter_1F_Text_OkayThisIsGood::
    .string "Okay, this is good…$"

OneIsland_PokemonCenter_1F_Text_LinkedUpWithLanette::
    .string "I did it!\n"
    .string "I linked up with LANETTE!$"

OneIsland_PokemonCenter_1F_Text_ManagedToLinkWithHoennThankYou::
    .string "{PLAYER}…\n"
    .string "{PLAYER}, I did it!\p"
    .string "I've managed to link up with\n"
    .string "TRAINERS in the HOENN region!\p"
    .string "Finally, the Network Machine is\n"
    .string "fully operational!\p"
    .string "{PLAYER}, I owe it all to you!\p"
    .string "Thanks to you, my dream came\n"
    .string "true…\p"
    .string "I want to give you something\n"
    .string "to thank you for all your help.$"

OneIsland_PokemonCenter_1F_Text_ExplainDive::
    .string "Sometimes while SURFING, you'll\n"
    .string "notice dark patches of water.\p"
    .string "The water there's deep, so you can\n"
    .string "use DIVE to drop to the seafloor.\p"
    .string "When you want to surface, you can\n"
    .string "use DIVE again as long there's\l"
    .string "nothing blocking you.$"

OneIsland_PokemonCenter_1F_Text_WishYouBestOfLuck::
    .string "I…\n"
    .string "I'm not crying.\p"
    .string "That's enough about me!\p"
    .string "{PLAYER}, you're going to keep\n"
    .string "looking for exotic POKéMON, right?\p"
    .string "I wish you the best of luck!$"

OneIsland_PokemonCenter_1F_Text_CelioHearingRumorsAboutYou::
    .string "CELIO: Hello!\p"
    .string "{PLAYER}, I've been hearing rumors\n"
    .string "about you.$"

OneIsland_PokemonCenter_1F_Text_BillsFirstMonWasAbra::
    .string "{PLAYER}, what's your favorite kind\n"
    .string "of POKéMON?\p"
    .string "BILL is a POKéMANIAC, so he loves\n"
    .string "every kind.\p"
    .string "Apparently, the first one he caught\n"
    .string "was an ABRA.$"

OneIsland_PokemonCenter_1F_Text_BillsHometownInGoldenrod::
    .string "By the way, {PLAYER}, you're from\n"
    .string "PALLET TOWN, aren't you?\p"
    .string "I've heard that it's a quiet and\n"
    .string "pleasant place.\p"
    .string "BILL's hometown is GOLDENROD CITY,\n"
    .string "where his folks still live.\p"
    .string "I've heard that it's quite the\n"
    .string "festive, bustling city.\p"
    .string "I'd like to go there one day.$"

OneIsland_PokemonCenter_1F_Text_BillCantStomachMilk::
    .string "{PLAYER}, is there anything that\n"
    .string "you can't stand?\p"
    .string "Apparently, BILL simply can't\n"
    .string "stomach milk at all.$"

OneIsland_PokemonCenter_1F_Text_CameFromPalletDontKnowIt::
    .string "Oh, you're a stranger here!\n"
    .string "Hi! Where did you come from?\p"
    .string "…PALLET TOWN?\n"
    .string "I don't know it!$"

OneIsland_PokemonCenter_1F_Text_EnormousVolcanoOnIsland::
    .string "On this island, there's an enormous\n"
    .string "volcano.\p"
    .string "It hasn't erupted lately, so why\n"
    .string "not enjoy a hike?$"

OneIsland_PokemonCenter_1F_Text_WishICouldTradeWithBoyfriend::
    .string "I wish I could trade POKéMON with\n"
    .string "my boyfriend who lives far away…$"

OneIsland_PokemonCenter_1F_Text_TradedWithFarAwayBoyfriend::
    .string "I traded POKéMON with my boyfriend\n"
    .string "far away!\p"
    .string "Everyone's saying that we can\n"
    .string "thank you and CELIO.\p"
    .string "So, thank you!$"

OneIsland_PokemonCenter_1F_Text_MachineUnderAdjustment::
    .string "Network Machine\n"
    .string "Link Level 0\p"
    .string "…POKéMON Storage System under\n"
    .string "adjustment…$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKanto::
    .string "Network Machine\n"
    .string "Link Level 1\p"
    .string "Link established with the KANTO\n"
    .string "region.$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKantoAndHoenn::
    .string "Network Machine\n"
    .string "Link Level 2\p"
    .string "Link established with the KANTO\n"
    .string "and HOENN regions.$"

OneIsland_PokemonCenter_1F_Text_ObtainedTriPass::
    .string "Obtained the TRI-PASS!$"

