ThreeIsland_DunsparceTunnel_Text_ProspectingForGold::
    .string "Hé toi!\n"
    .string "Comment ça va?\p"
    .string "Tu veux savoir ce que je fais?\n"
    .string "Je suis chercheur d'or.\p"
    .string "Quand je serai riche, j'achèterai\n"
    .string "une maison à KANTO.$"

ThreeIsland_DunsparceTunnel_Text_StruckGoldThisIsForYou::
    .string "Hé toi!\n"
    .string "Comment ça va?\p"
    .string "T'es au courant? J'ai trouvé de\n"
    .string "l'or! Tu peux pas t'imaginer\p"
    .string "comme je suis heureux.\p"
    .string "Allez, prends ça,\n"
    .string "ça me fait plaisir!$"

ThreeIsland_DunsparceTunnel_Text_ThatsANugget::
    .string "C'est un {STR_VAR_1}!\p"
    .string "Je n'en ai pas besoin.\n"
    .string "J'espère que ça te va!$"

ThreeIsland_DunsparceTunnel_Text_WhoopsBagCrammedFull::
    .string "Crotte, ton SAC est plein!\n"
    .string "Je te la donnerai une autre fois.$"

ThreeIsland_DunsparceTunnel_Text_ObtainedFossil::
    .string "{PLAYER} reçoit un {STR_VAR_1}!$"
