CeladonCity_DepartmentStore_2F_Text_SuperRepelMorePowerfulRepel::
    .string "SUPER REPEL keeps weak POKéMON at\n"
    .string "bay…\p"
    .string "Hmm, it's a more powerful REPEL.$"

CeladonCity_DepartmentStore_2F_Text_BuyReviveForLongOutings::
    .string "Equipe-toi de RAPPELS avant de\n"
    .string "partir à l'aventure$"

CeladonCity_DepartmentStore_2F_Text_FloorSign::
    .string "Les objets de premier choix!\p"
    .string "1er: MARCHE DES DRESSEURS$"

CeladonCity_DepartmentStore_2F_Text_LanceComesToBuyCapes::
    .string "PETER vient souvent ici pour\n"
    .string "acheter des capes.\p"
    .string "Je me demande combien de capes\n"
    .string "identiques il peut avoir chez lui.$"
