Aide_Text_HaventCaughtEnoughMonsForItem::
	.string "Voyons voir…\n"
	.string "Oh! Tu n'as attrapé que {STR_VAR_3}\l"
	.string "sortes de POKéMON!\p"
	.string "Il t'en faut {STR_VAR_1} différents pour\n"
	.string "mériter un {STR_VAR_2}.$"

Aide_Text_GetEnoughMonsComeBackForItem::
	.string "Dans ce cas…\p"
	.string "Reviens avec {STR_VAR_1} sortes de POKéMON,\n"
	.string "pour obtenir {STR_VAR_2}.$"

Aide_Text_DontHaveAnyRoomForItem::
	.string "Oh! Mais tu n'as plus assez\n"
	.string "de place pour le {STR_VAR_2}.$"
