Braille_Text_Up::
	.braille "HAUT$"

Braille_Text_Down::
	.braille "BAS$"

Braille_Text_Right::
	.braille "DROITE$"

Braille_Text_Left::
	.braille "GAUCHE$"

Braille_Text_Cut::
	.braille "COUPE$"

Braille_Text_ABC::
	.braille "ABC$"

Braille_Text_GHI::
	.braille "GHI$"

Braille_Text_MNO::
	.braille "MNO$"

Braille_Text_TUV::
	.braille "TUV$"

Braille_Text_DEF::
	.braille "DEF$"

Braille_Text_JKL::
	.braille "JKL$"

Braille_Text_PQRS::
	.braille "PQRS$"

Braille_Text_WXYZ::
	.braille "WXYZ$"

Braille_Text_Period::
	.braille ".$"

Braille_Text_Comma::
	.braille ",$"

Braille_Text_Everything::
	.braille "TOUT$"

Braille_Text_HasMeaning1::
	.braille "A UN SENS$"

Braille_Text_Existence::
	.braille "EXISTENCE$"

Braille_Text_HasMeaning2::
	.braille "A UN SENS$"

Braille_Text_BeingAlive::
	.braille "ETRE EN VIE$"

Braille_Text_HasMeaning3::
	.braille "A UN SENS$"

Braille_Text_HaveDreams::
	.braille "AVOIR DES REVES$"

Braille_Text_UsePower::
	.braille "UTILISER SA PUISSANCE.$"

Braille_Text_LetTheTwo::
	.braille "LAISSE LES DEUX$"

Braille_Text_Glittering::
	.braille "SCINTILLANT$"

Braille_Text_Stones::
	.braille "PIERRES$"

Braille_Text_OneInRed::
	.braille "UN EN ROUGE$"

Braille_Text_OneInBlue::
	.braille "UN EN BLEU$"

Braille_Text_ConnectThe::
	.braille "CONNECTE LES$"

Braille_Text_Past::
	.braille "PASSE.$"

Braille_Text_TwoFriends::
	.braille "DEUX AMIS$"

Braille_Text_Sharing::
	.braille "PARTAGER$"

Braille_Text_PowerOpen::
	.braille "POUVOIR EVEIL$"

Braille_Text_AWindowTo::
	.braille "UNE FENETRE VERS$"

Braille_Text_ANewWorld::
	.braille "LE NOUVEAU MONDE$"

Braille_Text_ThatGlows::
	.braille "CA BRILLE.$"

Braille_Text_TheNext::
	.braille "LE NOUVEAU$"

Braille_Text_WorldWaits::
	.braille "MONDE ATTEND$"

Braille_Text_ForYou::
	.braille "SON HERO.$"
