@ Same as Hoenn's day-care text, used by the Four Island Day-Care. Unused text translated in Emerald

DayCare_Text_ImDaycareManSpeakToMyWife::
	.string "Je suis l'HOTE DE LA PENSION.\p"
	.string "Je peux m'occuper des précieuxs\n"
	.string "POKéMON des dresseurs.\p"
	.string "Si tu veux que j'élève ton\n"
	.string "POKéMON, va parler à ma femme.$"

DayCare_Text_DoYouWantEgg::
	.string "Ah, c'es toi!\p"
	.string "Nous etions en train de s'occuper\n"
	.string "de ton POKéMON, et surprise!\p"
	.string "Ton POKéMON a un ŒUF!\p"
	.string "Nous ne savons pas comment\n"
	.string "mais c'est celui de ton POKéMON.\p"
	.string "Tu le veux?$"

DayCare_Text_YourMonIsDoingFine::
	.string "Ah, c'est toi! Content de te voir.\n"
	.string "Ton {STR_VAR_1} se porte bien.$"

DayCare_Text_IllKeepIt::
	.string "Très bien, je le garde alors.\n"
	.string "Merci!$"

DayCare_Text_YouHaveNoRoomForIt::
	.string "Tu n'as plus de place…\n"
	.string "Reviens quand tu auras de la\p"
	.string "place dans ton équipe.$"

DayCare_Text_ReceivedEgg::
	.string "{PLAYER} reçoit l'ŒUF de la part\n"
	.string "de l'HOTE DE LA PENSION.$"

DayCare_Text_TakeGoodCareOfIt::
	.string "Prends bien soin de lui.$"

DayCare_Text_YourMonsAreDoingFine::
	.string "Ah, c'est toi! Ton {STR_VAR_1} et\n"
	.string "ton {STR_VAR_2} vont bien.$"

DayCare_Text_IWillKeepDoYouWantIt::
	.string "Je vais le garder dans ce cas.\n"
	.string "Es-tu sûr de toi?$"

DayCare_Text_WouldYouLikeUsToRaiseMon::
	.string "Je suis l'HOTE DE LA PENSION.\p"
	.string "Nous pouvons élever tes POKéMON.\p"
	.string "Tu veux qu'on en élève un?$"

DayCare_Text_WhichMonShouldWeRaise::
	.string "Quel POKéMON veux-tu nous\n"
	.string "confier?$"

DayCare_Text_WellRaiseYourMon::
	.string "Bien, nous nous occuperons de {STR_VAR_1}\n"
	.string "jusqu'à nouvel ordre.\p"
	.string "Reviens pour le récupérer.$"

DayCare_Text_WeCanRaiseOneMore::
	.string "Nous pouvons élever deux POKéMON.\p"
	.string "Tu veux qu'on en élève un autre ?$"

DayCare_Text_HusbandWasLookingForYou::
	.string "Mon mari te cherche.$"

DayCare_Text_FineThenComeAgain::
	.string "Oh, ça marche.\n"
	.string "Reviens plus tard!$"

DayCare_Text_NotEnoughMoney::
	.string "Tu n'as pas assez d'argent…$"

DayCare_Text_TakeOtherOneBackToo::
	.string "Tu veux récupérer le deuxième?$"

DayCare_Text_ComeAgain::
	.string "Bien.\n"
	.string "Reviens plus tard.$"

DayCare_Text_GoodToSeeYou::
	.string "Ah, c'es toi!\n"
	.string "Content de te voir.\p"
	.string "Ton POKéMON se porte bien!$"

DayCare_Text_YourMonHasGrownXLevels::
	.string "Ton {STR_VAR_1} a gagné {STR_VAR_2}\n"
	.string "niveaux !$"

DayCare_Text_YourPartyIsFull::
	.string "Ton équipe est pleine!\n"
	.string "Fais de la place et reviens me voir.$"

DayCare_Text_ItWillCostX::
	.string "Si tu veux récupérer ton {STR_VAR_1},\n"
	.string "cela te coutera ¥{STR_VAR_2}.$"

DayCare_Text_HeresYourMon::
	.string "Parfait!\n"
	.string "Voici ton POKéMON.$"

DayCare_Text_TookBackMon::
	.string "{PLAYER} à récupéré {STR_VAR_2} de\n"
	.string "l'HOTE DE LA PENSION.$"

DayCare_Text_YouHaveJustOneMon::
	.string "Oh? Mais tu n'as qu'un seul\n"
	.string "POKéMON.\p"
	.string "Reviens plus tard.$"

DayCare_Text_TakeYourMonBack::
	.string "Veux-tu récupérer ton POKéMON?$"

DayCare_Text_WhatWillYouBattleWith::
	.string "Si tu me laisses ton POKéMON,\n"
	.string "qui va te défendre?\p"
	.string "Reviens plus tard.$"

DayCare_Text_Huh::
	.string "Hein?$"
