gFameCheckerFlavorText_ProfOak0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne ?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Labo Pokémon de Chen$"

gFameCheckerFlavorText_ProfOak1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Faire un guide complet sur\n"
	.string "les Pokémon du monde entier…\p"
	.string "C'est mon rêve!$"

gFameCheckerFlavorText_ProfOak2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le Prof. Chen est une célébrité\n"
	.string "dans le monde des POKéMON.\p"
	.string "Nombreux sont les Dresseurs\n"
	.string "qui lui portent un grand respect..$"

gFameCheckerFlavorText_ProfOak3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famille et amis?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le Prof. Chen vit avec sa\n"
	.string "petite-fille Nina et {RIVAL}.$"

gFameCheckerFlavorText_ProfOak4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famille et amis?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il paraît qu'il place de grands\n"
	.string "espoirs en toi.\p"
	.string "Autrefois, il était impressionnant\n"
	.string "de force et de beauté.\p"
	.string "C'était il y a des dizaines d'années,\n"
	.string "maintenant, il se consacre à ses études.$"

gFameCheckerFlavorText_ProfOak5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le Prof. Chen va avoir sa propre\n"
	.string "émission de radio.\p"
	.string "Elle s'appellera le\n"
	.string "Séminaire du Prof. Chen.$"

gFameCheckerFlavorText_Daisy0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Nina est capable de dire si\n"
	.string "tes POKéMON t'aiment ou pas.\p"
	.string "À l'occasion, elle peut même\n"
	.string "s'en occuper pour toi.$"

gFameCheckerFlavorText_Daisy1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}À mon avis, c'est la personne\n"
	.string "que les POKéMON préfèrent.$"

gFameCheckerFlavorText_Daisy2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Elle adorait ses Pokémon et les\n"
	.string "traitait avec beaucoup d'amour.\p"
	.string "Le nom de cette petite fille,\n"
	.string "je crois que c'est Nina.$"

gFameCheckerFlavorText_Daisy3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famille et amis?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le Prof. Chen vit avec sa\n"
	.string "petite-fille Nina et {RIVAL}.$"

gFameCheckerFlavorText_Daisy4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Nina vient de BOURG PALETTE, elle\n"
	.string "boit du thé tous les jours et va\p"
	.string "souvent au CENTRE COMMERCIAL\n"
	.string "de CÉLADOPOLE pour en acheter.$"

gFameCheckerFlavorText_Daisy5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le grand Champion du concours\n"
	.string "Pokémon de printemps est\l"
	.string "Nina de BOURG PALETTE!$"

gFameCheckerFlavorText_Brock0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Champion d'Arène d'ARGENTA :\n"
	.string "Pierre!\l"
	.string "Le Dresseur dur comme la pierre!$"

gFameCheckerFlavorText_Brock1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON favoris?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mes POKéMON sont tous durs comme\n"
	.string "la pierre et mon esprit est clair\p"
	.string "comme de l'eau de roche.\n"
	.string "C'est ça ! Mes Pokémon favoris\p"
	.string "sont les Pokémon Roche.$"

gFameCheckerFlavorText_Brock2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il n'y a pas vraiment de Dresseurs\n"
	.string "sérieux par ici. Ils s'intéressent\p"
	.string "surtout aux insectes, rien de\n"
	.string "passionnant. Mais Pierre d'Argenta\p"
	.string "n'est pas comme ça, pas du tout.$"

gFameCheckerFlavorText_Brock3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}En plus d'être cool, Pierre est.\n"
	.string "aussi très fort.\p"
	.string "Je voudrais devenir Champion\n"
	.string "d'Arène comme lui.$"

gFameCheckerFlavorText_Brock4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je cherche des fossiles ici, sous le\n"
	.string "Mont Sélénite.\p"
	.string "Pierre de l'Arène d'Argenta\n"
	.string "vient souvent m'aider.$"

gFameCheckerFlavorText_Brock5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Pierre rigole rarement, mais\n"
	.string "il ne peut pas s'arrêter s'il commence.$"

gFameCheckerFlavorText_Misty0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Champion d'Arène d'Azuria :\n"
	.string "Ondine.\l"
	.string "La sirène en shorts!$"

gFameCheckerFlavorText_Misty1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Pokémon favoris?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ma tactique? Attaquer\n"
	.string "avec des POKéMON EAU!$"

gFameCheckerFlavorText_Misty2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ondine est un Dresseur toujours\n"
	.string "en apprentissage. Mais elle ne\p"
	.string "peut pas perdre contre quelqu'un comme toi!$"

gFameCheckerFlavorText_Misty3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}On voit souvent des Dresseurs avec\n"
	.string "des POKéMON EAU par ici.\p"
	.string "Ils disent qu'Ondine de l'Arène\n"
	.string "d'Azuria s'entraîne dans le coin.$"

gFameCheckerFlavorText_Misty4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ce cap sert souvent de point de\p"
	.string "rencontre aux amoureux. On dit\n"
	.string "qu'Ondine y aurait de grands espoirs.$"

gFameCheckerFlavorText_Misty5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}On raconte qu'elle adore\n"
	.string "Olga du Conseil des 4.$"

gFameCheckerFlavorText_LtSurge0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Champion d'Arène de Carmin sur Mer :\n"
	.string "Major Bob,\l"
	.string "l'américain survolté!$"

gFameCheckerFlavorText_LtSurge1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Pokémon favoris?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je vais t'avouer quelque chose,\p"
	.string "les Pokémon Électrik m'ont sauvé!\n"
	.string "pendant la guerre!$"

gFameCheckerFlavorText_LtSurge2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}À l'armée, Major Bob était mon\n"
	.string "supérieur. C'était très instructif\p"
	.string "d'être sous ses ordres.$"

gFameCheckerFlavorText_LtSurge3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le Major Bob a toujours été\n"
	.string "reconnu pour sa nature prudente.$"

gFameCheckerFlavorText_LtSurge4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}C'est le Major Bob lui-même qui a\n"
	.string "installé les pièges de cette Arène.\p"
	.string "Il a mis des doubles verrous partout.$"

gFameCheckerFlavorText_LtSurge5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il aurait été pilote quand\n"
	.string "il était dans l'armée.\p"
	.string "Il utilisait l'électricité de ses\n"
	.string "POKéMON pour faire voler son avion.$"

gFameCheckerFlavorText_Erika0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Champion d'Arène de Céladopole :\n"
	.string "Erika,\l"
	.string "le combat par les plantes!$"

gFameCheckerFlavorText_Erika1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Pokémon favoris?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}J'étudie l'art des bouquets garnis.\n"
	.string "Mes Pokémon sont uniquement\p"
	.string "de type Plante.$"

gFameCheckerFlavorText_Erika2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Notre Champion a beau être calme,\n"
	.string "elle fait beaucoup parler d'elle.$"

gFameCheckerFlavorText_Erika3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Dans cette Arène, on ne se bat\n"
	.string "qu'avec des Pokémon Plante.\p"
	.string "En fait, on les utilise aussi\n"
	.string "pour faire des compositions florales!$"

gFameCheckerFlavorText_Erika4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Pokémon favoris?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Pour ma part, je collectionne\n"
	.string "les plus beaux Pokémon.$"

gFameCheckerFlavorText_Erika5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Si vous arrivez sans prévenir\n"
	.string "à l'Arène de Céladopole,\l"
	.string "vous risquez de la voir dormir.$"

gFameCheckerFlavorText_Koga0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne ?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Arène Pokémon de Parmanie\n"
	.string "Champion : Koga\l"
	.string "Le ninja aux poisons redoutables$"

gFameCheckerFlavorText_Koga1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Pokémon favoris?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Prépare-toi à affronter\n"
	.string "mes terribles Pokémon Poison!$"

gFameCheckerFlavorText_Koga2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je garderai espoir même dans\n"
	.string "la défaite, selon l'enseignement\l"
	.string "de Koga, mon maître ninja.$"

gFameCheckerFlavorText_Koga3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famille et amis?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mon père est le Champion de\n"
	.string "cette ville. Je m'entraîne pour.\p"
	.string "utiliser des POKéMON poison,\n"
	.string "comme lui.$"

gFameCheckerFlavorText_Koga4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il est incollable en médecine.\n"
	.string "On dit qu'il prépare lui-même\p"
	.string "ses médicaments pour soigner\n"
	.string "ses POKéMON.$"

gFameCheckerFlavorText_Koga5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le Parc Safari est immense,\n"
	.string "tu trouves pas?\p"
	.string "Koga, le Champion d'Arène de\n"
	.string "Parmanie vient souvent s'entraîner ici.\p"
	.string "Grâce à lui, on peut se\n"
	.string "promener en sécurité.$"

gFameCheckerFlavorText_Sabrina0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Arène Pokémon de Safrania\n"
	.string "Champion : Morgane\l"
	.string "Maîtresse des POKéMON psy!$"

gFameCheckerFlavorText_Sabrina1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Pokémon favoris?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}T'as entendu parler d'une fille\n"
	.string "Champion d'Arène de Safrania?\p"
	.string "Elle utilise des Pokémon psy,\n"
	.string "c'est bien ça?$"

gFameCheckerFlavorText_Sabrina2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}J'ai des pouvoirs psychiques depuis\n"
	.string "l'enfance. J'ai appris à plier\p"
	.string "des cuillères par la force\n"
	.string "de mon esprit.$"

gFameCheckerFlavorText_Sabrina3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je n'aime pas les combats,\n"
	.string "mais si tu insistes,\p"
	.string "je vais de montrer mes pouvoirs!$"

gFameCheckerFlavorText_Sabrina4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Les gens racontent qu'elle peut\n"
	.string "communiquer avec ses POKéMON\l"
	.string "pendant les combats juste par la pensée.$"

gFameCheckerFlavorText_Sabrina5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Morgane a pulvérisé le\n"
	.string "grand maître de karaté!$"

gFameCheckerFlavorText_Blaine0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Arène Pokémon de Cramois'Île\n"
	.string "Champion : Auguste\l"
	.string "Le maître du quiz!$"

gFameCheckerFlavorText_Blaine1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Pokémon favoris?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mes Pokémon flamboyants\n"
	.string "vont te réduire en cendres!$"

gFameCheckerFlavorText_Blaine2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Pokémon favoris?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Tout petit, Auguste aimait se\n"
	.string "promener dans les montagnes.\p"
	.string "Une nuit, il s'est retrouvé complètement\n"
	.string "perdu ! Mais un POKéMON oiseau apparut.\p"
	.string "La lumière de ses ailes enflammées\n"
	.string "permit à Auguste de retrouver\p"
	.string "son chemin ! Depuis il adore\n"
	.string "les POKéMON feu!$"

gFameCheckerFlavorText_Blaine3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Auguste, de l'Arène de Cramois'Île\n"
	.string "est un type étrange.\p"
	.string "Il vit ici depuis bien avant\n"
	.string "la construction du laboratoire.$"

gFameCheckerFlavorText_Blaine4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famille et amis ?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}C'est une photo d'Auguste et\n"
	.string "de M. Fuji.\p"
	.string "Ils sont côte à côte en souriant.$"

gFameCheckerFlavorText_Blaine5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Auguste passe tout son temps\n"
	.string "à créer des questions pour son quiz.$"

gFameCheckerFlavorText_Lorelei0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je zuis Olga du Conzeil 4!$"

gFameCheckerFlavorText_Lorelei1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Pokémon favoris?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je zuis la maîtresse des Pokémon glaze!$"

gFameCheckerFlavorText_Lorelei2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Où est née cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Un Dresseur très fort et très connu\n"
	.string "vient de cette île. Je suis sûr\p"
	.string "que même toi tu connais son nom.\n"
	.string "C'est Olga, du Conseil 4.$"

gFameCheckerFlavorText_Lorelei3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Connue pour sa logique et son\n"
	.string "style de combat très posé.\l"
	.string "Olga cache un terrible secret.$"

gFameCheckerFlavorText_Lorelei4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Tu savais qu'Olga a une collection\n"
	.string "de poupées ? Sa collection grandit\p"
	.string "à chaque fois qu'elle revient sur\n"
	.string "l'Ile 4.$"

gFameCheckerFlavorText_Lorelei5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Pokémon favoris?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Son Lokhlass, ça doit être celui\n"
	.string "qu'elle a depuis son enfance.\p"
	.string "Je crois qu'elle l'avait attrapé dans\n"
	.string "la Grotte de Glace.\p"
	.string "Ce Pokémon a dû passer\n"
	.string "des années avec elle.$"

gFameCheckerFlavorText_Bruno0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je suis Aldo du Conseil 4!$"

gFameCheckerFlavorText_Bruno1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Pokémon favoris?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}J'ai passé toute ma vie avec des\n"
	.string "Pokémon Combat, et ça n'est pas\p"
	.string "près de changer!$"

gFameCheckerFlavorText_Bruno2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Aldo a rejoint le Conseil 4 pour\n"
	.string "pouvoir affronter les meilleurs\l"
	.string "Dresseurs du monde.$"

gFameCheckerFlavorText_Bruno3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Aldo va souvent aux sources thermales.\n"
	.string "Il y va pour soigner ses blessures\p"
	.string "et celles de ses Pokémon.$"

gFameCheckerFlavorText_Bruno4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il fait partie du Conseil 4,\n"
	.string "il s'appelle Aldo.\p"
	.string "Il est reparti très déçu quand il\n"
	.string "a vu que les Super Bonbons étaient\l"
	.string "en rupture de stock partout.$"

gFameCheckerFlavorText_Bruno5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famille et amis?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Même Aldo… Avant il\n"
	.string "s'entraînait avec un gars qui\l"
	.string "s'appelle Bastien.$"

gFameCheckerFlavorText_Agatha0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je suis Agatha du Conseil 4 !$"

gFameCheckerFlavorText_Agatha1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Pokémon favoris?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Les Pokémon Spectre\n"
	.string "d'Agatha sont terrifiants.$"

gFameCheckerFlavorText_Agatha2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Agatha se met facilement en rogne!\n"
	.string "J'te raconte pas.$"

gFameCheckerFlavorText_Agatha3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Dans sa jeunesse, Agatha était la\n"
	.string "rivale du Prof. Chen.\p" 
	.string "Ils s'affrontaient pour obtenir\l"
	.string "le titre du meilleur Dresseur.$"

gFameCheckerFlavorText_Agatha4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famille et ?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il paraît que Chen place de grands\n"
	.string "espoirs en toi. Autrefois, il était\p"
	.string "impressionnant de force et de beauté.\n"
	.string "C'était il y a des dizaines d'années,\p"
	.string "maintenant, il se consacre à ses études.$"

gFameCheckerFlavorText_Agatha5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Prends Agatha par exemple.\p"
	.string "C'est la personne la plus âgée qui\n"
	.string "ait jamais fait partie du Conseil 4.$"

gFameCheckerFlavorText_Lance0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je règne sur le Conseil 4!\p"
	.string "Mon nom est Peter,\n"
	.string "le Dresseur de dragons!$"

gFameCheckerFlavorText_Lance1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Pokémon favoris?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Les dragons sont des POKéMON\n"
	.string "mythiques ! Les capturer et les\p"
	.string "entraîner est difficile, mais leurs\n"
	.string "pouvoirs sont supérieurs!\p"
	.string "Ils sont presque invincibles!$"

gFameCheckerFlavorText_Lance2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il défend la justice ! Il est posé\n"
	.string "et pourtant passioné!\l"
	.string "C'est le plus grand, c'est Peter!$"

gFameCheckerFlavorText_Lance3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Peter vient souvent ici pour acheter\n"
	.string "des capes. Je me demande combien\p"
	.string "de capes identiques il peut\n"
	.string "avoir chez lui.$"

gFameCheckerFlavorText_Lance4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famille et amis?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le grand-père de Peter est le\n"
	.string "doyen du célèbre clan des\l"
	.string "maîtres dragon.$"

gFameCheckerFlavorText_Lance5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famille et amis?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Y'a un copain d'un cousin d'une\n"
	.string "amie qui dit que Peter a un cousin\l"
	.string "Champion d'Arène quelque part.$"

gFameCheckerFlavorText_Bill0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Tout l'monde sait que Léo est un\n"
	.string "POKéMANIAC.\p"
	.string "Il a même inventé le stockage\n"
	.string "des Pokémon sur PC!$"

gFameCheckerFlavorText_Bill1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Pokémon favoris?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Léo a une sacrée collection de\n"
	.string "POKéMON! Et des rares, en plus!$"

gFameCheckerFlavorText_Bill2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}C'est mon petit-fils!\p"
	.string "Il souffre de collectionnite\n"
	.string "depuis son enfance!$"

gFameCheckerFlavorText_Bill3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON favoris?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Léo est un POKéMANIAC, il aime\n"
	.string "tous les types de POKéMON.\p"
	.string "Apparemment, son premier POKéMON\n"
	.string "était un ABRA.$"

gFameCheckerFlavorText_Bill4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famille et amis?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Léo vient de DOUBLONVILLE,\n"
	.string "sa famille y habite toujours.\p"
	.string "On raconte que c'est une ville\n"
	.string "qui aime faire la fête.$"

gFameCheckerFlavorText_Bill5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Apparemment, Léo est allergique\n"
	.string "au lait, c'est dingue.$"

gFameCheckerFlavorText_MrFuji0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}C'est vraiment un chic type!\p"
	.string "Il est à la recherche des POKéMON\n"
	.string "orphelins et abandonnés!$"

gFameCheckerFlavorText_MrFuji1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ce viel homme est venu nous\n"
	.string "demander de ne plus troubler\p"
	.string "les gentils POKéMON!\n"
	.string "Alors on a discuté tranquillement\p"
	.string "entre adultes.$"

gFameCheckerFlavorText_MrFuji2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Grand concours de dessin du magazine\n"
	.string "des fans de Pokémon!\p"
	.string "Le formulaire d'inscription est…\p"
	.string "Il a disparu ! Quelqu'un a déjà dû l'utiliser.$"

gFameCheckerFlavorText_MrFuji3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Il y a une rumeur…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il paraît que Mr. Fuji\n"
	.string "n'est pas non plus du coin.$"

gFameCheckerFlavorText_MrFuji4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famille et amis?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}C'est une photo d'Auguste et de\n"
	.string "Mr. Fuji.\p"
	.string "Ils sont côte à côte en souriant.$"

gFameCheckerFlavorText_MrFuji5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le timide Mr. Fuji a décliné\n"
	.string "notre demande d'interview.\p"
	.string "Cet homme très gentil est très\n"
	.string "apprécié à Lavanville.$"

gFameCheckerFlavorText_Giovanni0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Pour financer ses plans, la TEAM ROCKET\n"
	.string "a besoin de Pokémon!\p"
	.string "Pour ça, nous en capturons dans\n"
	.string "e monde entier.\p"
	.string "Et je suis le chef, moi… Giovanni!$"

gFameCheckerFlavorText_Giovanni1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Pokémon favoris?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ces types qui ont pris l'immeuble…\n"
	.string "Leur chef a dit qu'il cherchait\p"
	.string "des Pokémon costauds.$"

gFameCheckerFlavorText_Giovanni2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Le chef de la Team Rocket est\n"
	.string "incroyablement cruel.\p"
	.string "Pour lui, les Pokémon ne\n"
	.string "sont que des outils.$"

gFameCheckerFlavorText_Giovanni3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comment est cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Te voici dans mon repaire!\p"
	.string "Je voulais reformer la\n"
	.string "TEAM ROCKET ici!$"

gFameCheckerFlavorText_Giovanni4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Que fait cette personne?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Quoi ?! C'était Giovanni\n"
	.string "le Champion? Ben ça alors!$"

gFameCheckerFlavorText_Giovanni5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famille et amis?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Tu n'es pas le gamin de Giovanni,\n"
	.string "n'est-ce pas ? Non, impossible !\p"
	.string "Son gamin a les cheveux rouges.$"


gFameCheckerPersonName_ProfOak::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}PROF. CHEN$"

gFameCheckerPersonQuote_ProfOak::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: PROF. CHEN\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Pourquoi tes POKéMON se battent aussi\n"
	.string "fort pour réussite?\p"
	.string "Ils le font car ils peuvent voir en\n"
	.string "l'amour et la confiance que tu as\l"
	.string "pour les POKéMON.\p"
	.string "N'oublies jamais cela.$"

gFameCheckerPersonName_Daisy::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}NINA$"

gFameCheckerPersonQuote_Daisy::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: NINA\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Pendant que j'étais tranquillement\n"
	.string "en train de boire mon thé, tu es\l"
	.string "devenu extrêmement puissant.\p"
	.string "J'espère que tu restera le plus grand\n"
	.string "Rival de mon petit frère.$"

gFameCheckerPersonName_Brock::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}PIERRE$"

gFameCheckerPersonQuote_Brock::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: PIERRE\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Dans ce monde qui est le notre, il\n"
	.string "doit y avoir des tonnes de DRESSEURS.\p"
	.string "Continuons de nous entraîner\n"
	.string "et à nous rendre plus forts!$"

gFameCheckerPersonName_Misty::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}ONDINE$"

gFameCheckerPersonQuote_Misty::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: ONDINE\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je vais continuer de m'entraîner\n"
	.string "ici, dans cette ARENE.\p"
	.string "Quand je serais devenue plus forte je\n"
	.string "voudrais prendre la route et voyager.$"

gFameCheckerPersonName_LtSurge::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MAJOR BOB$"

gFameCheckerPersonQuote_LtSurge::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: MAJOR BOB\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hey, petit!\n"
	.string "Tu m'as foudroyé pendant notre combat!\p"
	.string "Je ne pensais pas qu'il éxistait des\n"
	.string "aussi imprévisible que toi.\p"
	.string "C'est ce qui m'a fait changé d'avis\n"
	.string "à ton sujet!$"

gFameCheckerPersonName_Erika::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}ERIKA$"

gFameCheckerPersonQuote_Erika::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: ERIKA\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je suis si heureuse qu'il existe des\n"
	.string "DRESSEURS aussi fort que toi.\p"
	.string "Cette prise de conscience suffit à\n"
	.string "me motiver et à persévérer.\p"
	.string "S'il te plait reviens me voir.\n"
	.string "Zzz…$"

gFameCheckerPersonName_Koga::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}KOGA$"

gFameCheckerPersonQuote_Koga::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: KOGA\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Toi et moi, nous devons continuer\n"
	.string "à viser toujours plus haut pour\l"
	.string "atteindre nos objectifs. A présent je\p"
	.string "dois commencer l'entraînement de ma fille.$"

gFameCheckerPersonName_Sabrina::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MORGANE$"

gFameCheckerPersonQuote_Sabrina::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: MORGANE\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}L'amour que tu portes à tes\n"
	.string "POKéMON…\p"
	.string "C'est un puissance que ne pourrais\n"
	.string "jamais contrer avec mes pouvoir psychiques.$"

gFameCheckerPersonName_Blaine::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}AUGUSTE$"

gFameCheckerPersonQuote_Blaine::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: AUGUSTE\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mes POKéMON FEU!\n"
	.string "Ils deviennent de plus en plus forts!\p"
	.string "Et maintenant question : combien de\n"
	.string "POKéMON de type FEU existent?$"

gFameCheckerPersonName_Lorelei::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}OLGA$"

gFameCheckerPersonQuote_Lorelei::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: OLGA\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je voudrais te remercier pour ton\n"
	.string "aide.\p"
	.string "Mais cela ne rentrera pas en compte\n"
	.string "dans nos futurs affrontements.\p"
	.string "Tu ferais mieux de t'entraîner d'ici là!$"

gFameCheckerPersonName_Bruno::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}ALDO$"

gFameCheckerPersonQuote_Bruno::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: ALDO\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}La surpuissance de tes POKéMON\n"
	.string "et toi, je n'ai pas pu la contenir.\p"
	.string "La prochaine fois, nous devrions\n"
	.string "nous entraîner ensemble.$"

gFameCheckerPersonName_Agatha::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}AGATHA$"

gFameCheckerPersonQuote_Agatha::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: AGATHA\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Quand tu vieilliras, ne deviens\n"
	.string "pas comme le PROF. CHEN!\p"
	.string "Fais comme moi et continue a te battre!$"

gFameCheckerPersonName_Lance::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}PETER$"

gFameCheckerPersonQuote_Lance::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: PETER\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}J'envisage de retourner sur ma\n"
	.string "terre natale.\p"
	.string "Je voudrais entraîner mes POKéMON DRAGON\n"
	.string "et les rendre plus forts.\p"
	.string "Je t'inviterais chez moi\n"
	.string "un de ces quatre.$"

gFameCheckerPersonName_Bill::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LEO$"

gFameCheckerPersonQuote_Bill::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: LEO\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Salut l'ami! CILEO n'a que de\n"
	.string "l'admiration pour toi.\p"
	.string "Cela me rend heureux de savoir cela.\p"
	.string "Quand tu attrapes des POKéMON rares,\n"
	.string "viens me les montrer, ok? Promets-le moi!$"

gFameCheckerPersonName_MrFuji::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MR. FUJI$"

gFameCheckerPersonQuote_MrFuji::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: MR. FUJI\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Au lieu d'espérer le bonheur de tes\n"
	.string "POKéMON…\p"
	.string "…Est-ce que je peux simplement souhaiter\n"
	.string "le bonheur de tous les POKéMON?$"

gFameCheckerPersonName_Giovanni::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}GIOVANNI$"

gFameCheckerPersonQuote_Giovanni::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}De: GIOVANNI\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Je n'ai rien à te dire\p"
	.string "Je vais faire en sorte de devenir\n"
	.string "beaucoup plus fort, c'est tout.$"

gFameCheckerFlavorTextOriginLocation_ProfOak0::
	.string "BOURG PALETTE$"

gFameCheckerFlavorTextOriginLocation_ProfOak1::
	.string "LABORATOIRE DU PROF. CHEN$"

gFameCheckerFlavorTextOriginLocation_ProfOak2::
	.string "LABORATOIRE DU PROF. CHEN$"

gFameCheckerFlavorTextOriginLocation_ProfOak3::
	.string "JADIELLE$"

gFameCheckerFlavorTextOriginLocation_ProfOak4::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_ProfOak5::
	.string "LABORATOIRE DU PROF. CHEN$"

gFameCheckerFlavorTextOriginLocation_Daisy0::
	.string "LABORATOIRE DU PROF. CHEN$"

gFameCheckerFlavorTextOriginLocation_Daisy1::
	.string "CARMIN SUR MER$"

gFameCheckerFlavorTextOriginLocation_Daisy2::
	.string "LABYRINTHE D'O$"

gFameCheckerFlavorTextOriginLocation_Daisy3::
	.string "JADIELLE$"

gFameCheckerFlavorTextOriginLocation_Daisy4::
	.string "RESIDENCE CELADON$"

gFameCheckerFlavorTextOriginLocation_Daisy5::
	.string "Île 4$"

gFameCheckerFlavorTextOriginLocation_Brock0::
	.string "ARGENTA$"

gFameCheckerFlavorTextOriginLocation_Brock1::
	.string "ARENE D'ARGENTA$"

gFameCheckerFlavorTextOriginLocation_Brock2::
	.string "ARGENTA$"

gFameCheckerFlavorTextOriginLocation_Brock3::
	.string "ROUTE 4$"

gFameCheckerFlavorTextOriginLocation_Brock4::
	.string "MONT SELENITE$"

gFameCheckerFlavorTextOriginLocation_Brock5::
	.string "MUSEE D'ARGENTA$"

gFameCheckerFlavorTextOriginLocation_Misty0::
	.string "AZURIA$"

gFameCheckerFlavorTextOriginLocation_Misty1::
	.string "ARENE D'AZURIA$"

gFameCheckerFlavorTextOriginLocation_Misty2::
	.string "ARENE D'AZURIA$"

gFameCheckerFlavorTextOriginLocation_Misty3::
	.string "ÎLES ECUME$"

gFameCheckerFlavorTextOriginLocation_Misty4::
	.string "CAP DES AMOUREUX$"

gFameCheckerFlavorTextOriginLocation_Misty5::
	.string "AZURIA$"

gFameCheckerFlavorTextOriginLocation_LtSurge0::
	.string "CARMIN SUR MER$"

gFameCheckerFlavorTextOriginLocation_LtSurge1::
	.string "ARENE DE CARMIN SUR MER$"

gFameCheckerFlavorTextOriginLocation_LtSurge2::
	.string "ARENE DE CARMIN SUR MER$"

gFameCheckerFlavorTextOriginLocation_LtSurge3::
	.string "ARENE DE CARMIN SUR MER$"

gFameCheckerFlavorTextOriginLocation_LtSurge4::
	.string "ARENE DE CARMIN SUR MER$"

gFameCheckerFlavorTextOriginLocation_LtSurge5::
	.string "CARMIN SUR MER$"

gFameCheckerFlavorTextOriginLocation_Erika0::
	.string "CELADOPOLE$"

gFameCheckerFlavorTextOriginLocation_Erika1::
	.string "ARENE DE CELADOPOLE$"

gFameCheckerFlavorTextOriginLocation_Erika2::
	.string "ARENE DE CELADOPOLE$"

gFameCheckerFlavorTextOriginLocation_Erika3::
	.string "ARENE DE CELADOPOLE$"

gFameCheckerFlavorTextOriginLocation_Erika4::
	.string "ARENE DE CELADOPOLE$"

gFameCheckerFlavorTextOriginLocation_Erika5::
	.string "RESIDENCE CELADON$"

gFameCheckerFlavorTextOriginLocation_Koga0::
	.string "PARMANIE$"

gFameCheckerFlavorTextOriginLocation_Koga1::
	.string "PARMANIE$"

gFameCheckerFlavorTextOriginLocation_Koga2::
	.string "PARMANIE$"

gFameCheckerFlavorTextOriginLocation_Koga3::
	.string "PARMANIE$"

gFameCheckerFlavorTextOriginLocation_Koga4::
	.string "PARMANIE$"

gFameCheckerFlavorTextOriginLocation_Koga5::
	.string "PARC SAFARI$"

gFameCheckerFlavorTextOriginLocation_Sabrina0::
	.string "SAFRANIA CITY$"

gFameCheckerFlavorTextOriginLocation_Sabrina1::
	.string "ÎLE 3$"

gFameCheckerFlavorTextOriginLocation_Sabrina2::
	.string "ARENE DE SAFRANIA$"

gFameCheckerFlavorTextOriginLocation_Sabrina3::
	.string "ARENE DE SAFRANIA$"

gFameCheckerFlavorTextOriginLocation_Sabrina4::
	.string "SAFRANIA$"

gFameCheckerFlavorTextOriginLocation_Sabrina5::
	.string "ARENE DE SAFRANIA$"

gFameCheckerFlavorTextOriginLocation_Blaine0::
	.string "CRAMOIS'ÎLE$"

gFameCheckerFlavorTextOriginLocation_Blaine1::
	.string "ARENE DE CRAMOIS'ÎLE$"

gFameCheckerFlavorTextOriginLocation_Blaine2::
	.string "ARENE DE CRAMOIS'ÎLE$"

gFameCheckerFlavorTextOriginLocation_Blaine3::
	.string "CRAMOIS'ÎLE$"

gFameCheckerFlavorTextOriginLocation_Blaine4::
	.string "ARENE DE CRAMOIS'ÎLE$"

gFameCheckerFlavorTextOriginLocation_Blaine5::
	.string "CAMP DE VACANCES$"

gFameCheckerFlavorTextOriginLocation_Lorelei0::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_Lorelei1::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_Lorelei2::
	.string "ÎLE 4$"

gFameCheckerFlavorTextOriginLocation_Lorelei3::
	.string "ÎLE 5$"

gFameCheckerFlavorTextOriginLocation_Lorelei4::
	.string "ÎLE 4$"

gFameCheckerFlavorTextOriginLocation_Lorelei5::
	.string "ÎLE 4$"

gFameCheckerFlavorTextOriginLocation_Bruno0::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_Bruno1::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_Bruno2::
	.string "SAFRANIA$"

gFameCheckerFlavorTextOriginLocation_Bruno3::
	.string "SOURCE BRAISE$"

gFameCheckerFlavorTextOriginLocation_Bruno4::
	.string "ÎLE 2$"

gFameCheckerFlavorTextOriginLocation_Bruno5::
	.string "CANYON SESOR$"

gFameCheckerFlavorTextOriginLocation_Agatha0::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_Agatha1::
	.string "PLEATEAU INDIGO$"

gFameCheckerFlavorTextOriginLocation_Agatha2::
	.string "PLATEAU INDIGO$"

gFameCheckerFlavorTextOriginLocation_Agatha3::
	.string "ÎLE 7$"

gFameCheckerFlavorTextOriginLocation_Agatha4::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_Agatha5::
	.string "ÎLE 6$"

gFameCheckerFlavorTextOriginLocation_Lance0::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_Lance1::
	.string "LIGUE POKéMON$"

gFameCheckerFlavorTextOriginLocation_Lance2::
	.string "SAFRANIA$"

gFameCheckerFlavorTextOriginLocation_Lance3::
	.string "CENTRE COMMERCIAL$"

gFameCheckerFlavorTextOriginLocation_Lance4::
	.string "PLATEAU INDIGO$"

gFameCheckerFlavorTextOriginLocation_Lance5::
	.string "PLATEAU INDIGO$"

gFameCheckerFlavorTextOriginLocation_Bill0::
	.string "AZURIA$"

gFameCheckerFlavorTextOriginLocation_Bill1::
	.string "AZURIA$"

gFameCheckerFlavorTextOriginLocation_Bill2::
	.string "PARMANIE$"

gFameCheckerFlavorTextOriginLocation_Bill3::
	.string "ÎLE 1$"

gFameCheckerFlavorTextOriginLocation_Bill4::
	.string "ÎLE 1$"

gFameCheckerFlavorTextOriginLocation_Bill5::
	.string "ÎLE 1$"

gFameCheckerFlavorTextOriginLocation_MrFuji0::
	.string "LAVANVILLE$"

gFameCheckerFlavorTextOriginLocation_MrFuji1::
	.string "TOUR POKéMON$"

gFameCheckerFlavorTextOriginLocation_MrFuji2::
	.string "LAVANVILLE$"

gFameCheckerFlavorTextOriginLocation_MrFuji3::
	.string "LAVANVILLE$"

gFameCheckerFlavorTextOriginLocation_MrFuji4::
	.string "ARENE DE CRAMOIS'ÎLE$"

gFameCheckerFlavorTextOriginLocation_MrFuji5::
	.string "CRAMOIS'ÎLE$"

gFameCheckerFlavorTextOriginLocation_Giovanni0::
	.string "REPAIRE ROCKET$"

gFameCheckerFlavorTextOriginLocation_Giovanni1::
	.string "SYLPHE SARL$"

gFameCheckerFlavorTextOriginLocation_Giovanni2::
	.string "SYLPHE SARL$"

gFameCheckerFlavorTextOriginLocation_Giovanni3::
	.string "ARENE DE JADIELLE$"

gFameCheckerFlavorTextOriginLocation_Giovanni4::
	.string "ARENE DE JADIELLE$"

gFameCheckerFlavorTextOriginLocation_Giovanni5::
	.string "ENTREPOT ROCKET$"

gFameCheckerFlavorTextOriginObjectName_ProfOak0::
	.string "PANNEAU$"

gFameCheckerFlavorTextOriginObjectName_ProfOak1::
	.string "PROF. CHEN$"

gFameCheckerFlavorTextOriginObjectName_ProfOak2::
	.string "ASSISTANT$"

gFameCheckerFlavorTextOriginObjectName_ProfOak3::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_ProfOak4::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_ProfOak5::
	.string "ASSISTANT$"

gFameCheckerFlavorTextOriginObjectName_Daisy0::
	.string "ASSISTANT$"

gFameCheckerFlavorTextOriginObjectName_Daisy1::
	.string "FEMME$"

gFameCheckerFlavorTextOriginObjectName_Daisy2::
	.string "HOMME$"

gFameCheckerFlavorTextOriginObjectName_Daisy3::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Daisy4::
	.string "VIEILLE FEMME$"

gFameCheckerFlavorTextOriginObjectName_Daisy5::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Brock0::
	.string "PANNEAU$"

gFameCheckerFlavorTextOriginObjectName_Brock1::
	.string "PIERRE$"

gFameCheckerFlavorTextOriginObjectName_Brock2::
	.string "JEUNE HOMME$"

gFameCheckerFlavorTextOriginObjectName_Brock3::
	.string "GARCON$"

gFameCheckerFlavorTextOriginObjectName_Brock4::
	.string "HOMME$"

gFameCheckerFlavorTextOriginObjectName_Brock5::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Misty0::
	.string "PANNEAU$"

gFameCheckerFlavorTextOriginObjectName_Misty1::
	.string "ONDINE$"

gFameCheckerFlavorTextOriginObjectName_Misty2::
	.string "LOUIS$"

gFameCheckerFlavorTextOriginObjectName_Misty3::
	.string "JEUNE HOMME$"

gFameCheckerFlavorTextOriginObjectName_Misty4::
	.string "FEMME$"

gFameCheckerFlavorTextOriginObjectName_Misty5::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_LtSurge0::
	.string "PANNEAU$"

gFameCheckerFlavorTextOriginObjectName_LtSurge1::
	.string "MAJOR BOB$"

gFameCheckerFlavorTextOriginObjectName_LtSurge2::
	.string "ANATOLE$"

gFameCheckerFlavorTextOriginObjectName_LtSurge3::
	.string "ANATOLE$"

gFameCheckerFlavorTextOriginObjectName_LtSurge4::
	.string "HAROLD$"

gFameCheckerFlavorTextOriginObjectName_LtSurge5::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Erika0::
	.string "PANNEAU$"

gFameCheckerFlavorTextOriginObjectName_Erika1::
	.string "ERIKA$"

gFameCheckerFlavorTextOriginObjectName_Erika2::
	.string "LOLA$"

gFameCheckerFlavorTextOriginObjectName_Erika3::
	.string "TAMIA$"

gFameCheckerFlavorTextOriginObjectName_Erika4::
	.string "ERIKA$"

gFameCheckerFlavorTextOriginObjectName_Erika5::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Koga0::
	.string "PANNEAU$"

gFameCheckerFlavorTextOriginObjectName_Koga1::
	.string "KOGA$"

gFameCheckerFlavorTextOriginObjectName_Koga2::
	.string "KIRK$"

gFameCheckerFlavorTextOriginObjectName_Koga3::
	.string "JANINE$"

gFameCheckerFlavorTextOriginObjectName_Koga4::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Koga5::
	.string "HOMME$"

gFameCheckerFlavorTextOriginObjectName_Sabrina0::
	.string "PANNEAU$"

gFameCheckerFlavorTextOriginObjectName_Sabrina1::
	.string "JEUNE HOMME$"

gFameCheckerFlavorTextOriginObjectName_Sabrina2::
	.string "MORGANE$"

gFameCheckerFlavorTextOriginObjectName_Sabrina3::
	.string "MORGANE$"

gFameCheckerFlavorTextOriginObjectName_Sabrina4::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Sabrina5::
	.string "TYRON$"

gFameCheckerFlavorTextOriginObjectName_Blaine0::
	.string "PANNEAU$"

gFameCheckerFlavorTextOriginObjectName_Blaine1::
	.string "AUGUSTE$"

gFameCheckerFlavorTextOriginObjectName_Blaine2::
	.string "DEREK$"

gFameCheckerFlavorTextOriginObjectName_Blaine3::
	.string "FEMME$"

gFameCheckerFlavorTextOriginObjectName_Blaine4::
	.string "PHOTO$"

gFameCheckerFlavorTextOriginObjectName_Blaine5::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Lorelei0::
	.string "OLGA$"

gFameCheckerFlavorTextOriginObjectName_Lorelei1::
	.string "OLGA$"

gFameCheckerFlavorTextOriginObjectName_Lorelei2::
	.string "VIEIL HOMME$"

gFameCheckerFlavorTextOriginObjectName_Lorelei3::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Lorelei4::
	.string "PETITE FILLE$"

gFameCheckerFlavorTextOriginObjectName_Lorelei5::
	.string "VIEILLE FEMME$"

gFameCheckerFlavorTextOriginObjectName_Bruno0::
	.string "ALDO$"

gFameCheckerFlavorTextOriginObjectName_Bruno1::
	.string "ALDO$"

gFameCheckerFlavorTextOriginObjectName_Bruno2::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Bruno3::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Bruno4::
	.string "FEMME$"

gFameCheckerFlavorTextOriginObjectName_Bruno5::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Agatha0::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_Agatha1::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Agatha2::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Agatha3::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Agatha4::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_Agatha5::
	.string "VIEILLE FEMME$"

gFameCheckerFlavorTextOriginObjectName_Lance0::
	.string "PETER$"

gFameCheckerFlavorTextOriginObjectName_Lance1::
	.string "PETER$"

gFameCheckerFlavorTextOriginObjectName_Lance2::
	.string "FEMME$"

gFameCheckerFlavorTextOriginObjectName_Lance3::
	.string "PETITE FILLE$"

gFameCheckerFlavorTextOriginObjectName_Lance4::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Lance5::
	.string "JEUNE HOMME$"

gFameCheckerFlavorTextOriginObjectName_Bill0::
	.string "{RIVAL}$"

gFameCheckerFlavorTextOriginObjectName_Bill1::
	.string "PETIT GARCON$"

gFameCheckerFlavorTextOriginObjectName_Bill2::
	.string "VIEIL HOMME$"

gFameCheckerFlavorTextOriginObjectName_Bill3::
	.string "CILEO$"

gFameCheckerFlavorTextOriginObjectName_Bill4::
	.string "CILEO$"

gFameCheckerFlavorTextOriginObjectName_Bill5::
	.string "CILEO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji0::
	.string "PETITE FILLE$"

gFameCheckerFlavorTextOriginObjectName_MrFuji1::
	.string "TEAM ROCKET$"

gFameCheckerFlavorTextOriginObjectName_MrFuji2::
	.string "MAGAZINE$"

gFameCheckerFlavorTextOriginObjectName_MrFuji3::
	.string "HOMME$"

gFameCheckerFlavorTextOriginObjectName_MrFuji4::
	.string "PHOTO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji5::
	.string "JOURNAL POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Giovanni0::
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni1::
	.string "SCIENTIFIQUE$"

gFameCheckerFlavorTextOriginObjectName_Giovanni2::
	.string "SCIENTIFIQUE$"

gFameCheckerFlavorTextOriginObjectName_Giovanni3::
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni4::
	.string "HOMME$"

gFameCheckerFlavorTextOriginObjectName_Giovanni5::
	.string "GEDEON$"

PokemonJournal_Text_SpecialFeatureBrock::
	.string "JOURNAL POKéMON\p"
	.string "Edition spéciale: ARENE D'ARGENTA\n"
	.string "PIERRE!\p"
	.string "PIERRE rigole rarement, mais il ne\n"
	.string "peut pas s'arrêter s'il commence.$"

PokemonJournal_Text_SpecialFeatureMisty::
	.string "JOURNAL POKéMON\p"
	.string "Edition spéciale: ARENE D'AZURIA\n"
	.string "ONDINE!\p"
	.string "On raconte qu'elle adore\n"
	.string "Olga du Conseil des 4.$"

PokemonJournal_Text_SpecialFeatureLtSurge::
	.string "JOURNAL POKéMON\p"
	.string "Edition spéciale: ARENE CARMIN SUR MER\n"
	.string "MAJOR BOB!\p"
	.string "Il aurait été pilote quand il était\n"
	.string "dans l'armée.\p"
	.string "Il utilisait l'électricité de ses\n"
	.string "POKéMON pour faire voler son avion.$"

PokemonJournal_Text_SpecialFeatureErika::
	.string "JOURNAL POKéMON\p"
	.string "Edition spéciale: ARENE DE CELADOPOLE\n"
	.string "ERIKA!\p"
	.string "Si vous arrivez sans prévenir à\n"
	.string "l'Arène de Céladopole,\l"
	.string "vous risquez de la voir dormir.$"

PokemonJournal_Text_SpecialFeatureKoga::
	.string "JOURNAL POKéMON\p"
	.string "Edition spéciale: ARENE DE PARMANIE\n"
	.string "KOGA!\p"
	.string "Il est incollable en médecine.\n"
	.string "On dit qu'il prépare lui-même ses\p"
	.string "médicaments pour soigner ses\n"
	.string "POKéMON.$"

PokemonJournal_Text_SpecialFeatureSabrina::
	.string "JOURNAL POKéMON\p"
	.string "Edition spéciale: ARENE DE SAFRANIA\n"
	.string "MORGANE!\p"
	.string "Les gens racontent qu'elle peut\n"
	.string "communiquer avec ses POKéMON\l"
	.string "pendant les combats juste par la pensée.$"

PokemonJournal_Text_SpecialFeatureBlaine::
	.string "JOURNAL POKéMON\p"
	.string "Edition spéciale: ARENE DE CRAMOIS'ILE\n"
	.string "AUGUSTE!\p"
	.string "Auguste passe tout son temps\n"
	.string "à créer des questions pour son quiz.$"

PokemonJournal_Text_SpecialFeatureLorelei::
	.string "JOURNAL POKéMON\p"
	.string "Edition spéciale:\n"
	.string "OLGA du CONSEIL 4!\p"
	.string "Connue pour sa logique et son\n"
	.string "style de combat très posé.\l"
	.string "Olga cache un terrible secret.$"

PokemonJournal_Text_SpecialFeatureBruno::
	.string "JOURNAL POKéMON\p"
	.string "Edition spéciale :\n"
	.string "ALDO du CONSEIL 4!\p"
	.string "Aldo a rejoint le Conseil 4 pour\n"
	.string "pouvoir affronter les meilleurs\l"
	.string "Dresseurs du monde.$"

PokemonJournal_Text_SpecialFeatureAgatha::
	.string "JOURNAL POKéMON\p"
	.string "Edition spéciale :\n"
	.string "AGATHA du CONSEIL 4!\p"
	.string "Dans sa jeunesse, Agatha était\n"
	.string "la rivale du Prof. Chen.\p"
	.string "Ils s'affrontaient pour obtenir le\n"
	.string "titre du meilleur Dresseur.$"

PokemonJournal_Text_SpecialFeatureLance::
	.string "JOURNAL POKéMON\p"
	.string "Edition spéciale :\n"
	.string "PETER du CONSEIL 4!\p"
	.string "Le grand-père de Peter est\n"
	.string "le doyen du célèbre clan\l"
	.string "des maîtres dragon.$"

PokemonJournal_Text_SpecialFeatureProfOak::
	.string "JOURNAL POKéMON\p"
	.string "Edition spéciale : PROF. CHEN,\n"
	.string "Le professeur POKéMON!\p"
	.string "Le Prof. Chen vit avec\n"
	.string "sa petite-fille Nina et {RIVAL}.$"

PokemonJournal_Text_SpecialFeatureDaisyOak::
	.string "C'est une vieille édition du\n"
	.string "JOURNAL POKéMON…\p"
	.string "JOURNAL POKéMON\n"
	.string "Edition spéciale concours!\p"
	.string "Le grand Champion du concours\n"
	.string "POKéMON de printemps est\l"
	.string "NINA de BOURG PALETTE.$"

PokemonJournal_Text_SpecialFeatureMrFuji::
	.string "JOURNAL POKéMON\p"
	.string "Edition spéciale :\n"
	.string "MR. FUJI de LAVANVILLE!\p"
	.string "Le timide Mr. Fuji a décliné notre\n"
	.string "demande d'interview.\p"
	.string "Cet homme très gentil est\n"
	.string "très apprécié à LAVANVILLE.$"
