@ Flavor text for interacting with various background objects

Text_Bookshelf::
	.string "Des bouquins sur les POKéMON.$"

Text_ATownMap::
	.string "UNE CARTE.$"

Text_PokeMartShelf::
	.string "Cool! Plein de machins sur les\n"
	.string "POKéMON!$"

Text_DishesPlatesNeatlyLinedUp::
	.string "La vaisselle et les assiettes\n"
	.string "sont bien rangées ici.$"

Text_Kitchen::
	.string "Quelqu'un a cuisiné ici,\n"
	.string "Ça sent vraiment bon.$"

Text_Dresser::
	.string "C'est une belle commode.\n"
	.string "On peut y ranger plein de trucs.$"

Text_Snacks::
	.string "Il y a un tas de nourriture ici.$"

Text_PokemartSign::
	.string "Faites le plein d'objets!\n"
	.string "BOUTIQUE POKéMON$"

Text_PokecenterSign::
	.string "Soignez vos POKéMON!\n"
	.string "CENTRE POKéMON$"

Text_Indigo_UltimateGoal::
	.string "PLATEAU INDIGO\p"
	.string "Le rêve de tout DRESSEUR!\n"
	.string "Quartier général de la LIGUE\p"
	.string "POKéMON$"

Text_Indigo_HighestAuthority::
	.string "PLATEAU INDIGO\p"
	.string "La plus haute instance POKéMON!\n"
	.string "Quartier général de la LIGUE\p"
	.string "POKéMON$"

Text_Food::
	.string "Il y a tout un tas de choses qui\n"
	.string "ont l'air délicieuses.$"

Text_Blueprints::
	.string "C'est une sorte de plan. Il y a.\n"
	.string "quelque chose d'écrit dessus.$"

Text_Painting::
	.string "Une belle image d'un POKéMON.\n"
	.string "Il semble heureux.$"

Text_PowerPlantMachine::
	.string "A quoi ça peut bien server? Mieux\n"
	.string "vaut ne pas y toucher!$"

Text_Telephone::
	.string "C'est un téléphone. Il vaut mieux\n"
	.string "ne pas l'utiliser.$"

Text_Computer::
	.string "C'est rempli de mots et de chiffres\n"
	.string "incompréhensibles…$"

Text_AdvertisingPoster::
	.string "C'est une publicité pour de\n"
	.string "nombreux articles.$"

Text_TastyFood::
	.string "Mmm, quelle bonne odeur.\n"
	.string "Ça donne vraiment faim!$"

Text_TrashBin::
	.string "Alors ici…\n"
	.string "……\p"
	.string "Il n'y a absolument rien!$"

Text_Cup::
	.string "C'est une tasse avec une\n"
	.string "marque de POKéMON.$"

Text_PolishedWindow::
	.string "Le fenêtre est très propre!$"

Text_BeautifulSkyWindow::
	.string "De l'autre côté de la fenêtre…\p"
	.string "Le ciel est d'une incroyable\n"
	.string "beauté.$"

Text_BlinkingLights::
	.string "Il y a plein de petites lampes\n"
	.string "qui clignotent.$"

Text_NeatlyLinedUpTools::
	.string "Plusieurs outils sont rangés ici.$"

Text_ImpressiveMachine::
	.string "C'est une sorte de machine.\n"
	.string "C'est impressionnant.$"

Text_VideoGame::
	.string "Une SUPER NINTENDO!$"

Text_Burglary::
	.string "Il y a des signes d'effraction ici…$"

Text_PlayerFacingTVScreen::
	.string "Une émision avec des POKéMON.\n"
	.string "Ça a l'air cool!$"
