Trade_Text_LookingForMonWannaTradeForMon::
	.string "Je suis à la recherche d'un\n"
	.string "{STR_VAR_1}!\p"
	.string "Tu veux m'en échanger un contre mon\n"
	.string "{STR_VAR_2}?$"

Trade_Text_AwwOhWell::
	.string "Awww!\n"
	.string "Très bien…$"

Trade_Text_WhatThatsNoMon::
	.string "Quoi?\n"
	.string "Ce n'est pas un {STR_VAR_1}!$"

Trade_Text_HeyThanks::
	.string "Hey, merci!$"

Trade_Text_IsntMyOldMonGreat::
	.string "Est-ce que mon {STR_VAR_2} va bien?$"

Trade_Text_DoYouHaveMonWouldYouTradeForMon::
	.string "Salutations! Aurais-tu par\n"
	.string "hasard un {STR_VAR_1}?\p"
	.string "Accepterais-tu de l'échanger\n"
	.string "contre mon {STR_VAR_2}?$"

Trade_Text_WellIfYouDontWantTo::
	.string "Ok, je comprends…$"

Trade_Text_ThisIsntMon::
	.string "Hmmm?\n"
	.string "Ce n'est pas un {STR_VAR_1}.\p"
	.string "Reviens quand tu en auras un.$"

Trade_Text_Thanks::
	.string "Merci!$"

Trade_Text_HasTradedMonGrownStronger::
	.string "Le {STR_VAR_2} que je t'ai échangé,\n"
	.string "est-il devenu plus fort?$"

Trade_Text_DoYouHaveMonWantToTradeForMon::
	.string "Salut!\n"
	.string "Possède-tu un {STR_VAR_1}?\p"
	.string "Tu veux l'échanger contre mon\n"
	.string "{STR_VAR_2}?$"

Trade_Text_ThatsTooBad::
	.string "Ca craint!$"

Trade_Text_ThisIsNoMon::
	.string "…Ce n'est pas un {STR_VAR_1}.\p"
	.string "Si tu en a un, viens me l'échanger.$"

Trade_Text_ThanksYoureAPal::
	.string "Merci mon pote!$"

Trade_Text_HowIsMyOldMon::
	.string "Comment va mon vieux {STR_VAR_2}?\n"
	.string "Mon {STR_VAR_1} se porte bien!$"
