gOtherText_NewName::
    .string "NOM:$"

gNameChoice_Green::
    .string "BLUE$"

gNameChoice_Red::
    .string "BLUE$"

gNameChoice_Leaf::
    .string "LEAF$"

gNameChoice_Fire::
    .string "FIRE$"

gNameChoice_Gary::
    .string "POLO$"

gNameChoice_Kaz::
    .string "TOM$"

gNameChoice_Toru::
    .string "TORU$"

gNameChoice_Ash::
    .string "DANNY$"

gNameChoice_Kene::
    .string "GURVAN$"

gNameChoice_Geki::
    .string "GONTRAN$"

gNameChoice_Jak::
    .string "AYRTON$"

gNameChoice_Janne::
    .string "FRANCK$"

gNameChoice_Jonn::
    .string "JONN$"

gNameChoice_Kamon::
    .string "KAMON$"

gNameChoice_Karl::
    .string "DAVY$"

gNameChoice_Taylor::
    .string "TAYLOR$"

gNameChoice_Oscar::
    .string "OSCAR$"

gNameChoice_Hiro::
    .string "HIRO$"

gNameChoice_Max::
    .string "MAX$"

gNameChoice_Jon::
    .string "JON$"

gNameChoice_Ralph::
    .string "RALPH$"

gNameChoice_Kay::
    .string "RALPH$"

gNameChoice_Tosh::
    .string "TOSH$"

gNameChoice_Roak::
    .string "ZACK$"

gNameChoice_Omi::
    .string "OMI$"

gNameChoice_Jodi::
    .string "JODI$"

gNameChoice_Amanda::
    .string "AMANDA$"

gNameChoice_Hillary::
    .string "HILLARY$"

gNameChoice_Makey::
    .string "MAKEY$"

gNameChoice_Michi::
    .string "MICHI$"

gNameChoice_Paula::
    .string "PAULA$"

gNameChoice_June::
    .string "JUNE$"

gNameChoice_Cassie::
    .string "CASSIE$"

gNameChoice_Rey::
    .string "REY$"

gNameChoice_Seda::
    .string "SEDA$"

gNameChoice_Kiko::
    .string "KIKO$"

gNameChoice_Mina::
    .string "MINA$"

gNameChoice_Norie::
    .string "NORIE$"

gNameChoice_Sai::
    .string "SAI$"

gNameChoice_Momo::
    .string "MOMO$"

gNameChoice_Suzi::
    .string "SUZI$"

gControlsGuide_Text_Intro::
    .string "Les différents boutons seront\n"
    .string "décrits par ordre d'importance.$"

gControlsGuide_Text_DPad::
    .string "Déplacer le personnage.\n"
    .string "Faire une sélection.$"

gControlsGuide_Text_AButton::
    .string "Confirmer un choix, observer,\n"
    .string "parler et faire défiler le texte.$"

gControlsGuide_Text_BButton::
    .string "Quitter, annuler un choix ou\n"
    .string "un mode.$"

gControlsGuide_Text_StartButton::
    .string "Ouvrir le menu.$"

gControlsGuide_Text_SelectButton::
    .string "Changer les objets ou utiliser\n"
    .string "un objet enregistré.$"

gControlsGuide_Text_LRButtons::
    .string "Obtenir de l'aide ou des\n"
    .string "explications pendant la partie.$"

gOakSpeech_Text_AskPlayerGender::
    .string "Maintenant dis-moi. Es-tu un\n"
    .string "garçon ou une fille?$"

gPikachuIntro_Text_Page1::
    .string "Bienvenue dans cette traduction\n"
    .string "française de la ROM FRLG Plus de\n"
    .string "Deokishisu.\n"
    .string "En l'absence de vraies bases de\n"
    .string "données pour récupérer les textes\n"
    .string "français originaux de 2004 j'ai\n"
    .string "fais au mieux pour rendre cette\n"
    .string "traduction possible.$"

gPikachuIntro_Text_Page2::
    .string "Si vous trouvez des dialogues mal\n"
    .string "traduits, des erreurs de synthaxes,\n"
    .string "des fautes de frappes ou des oublis\n"
    .string "lorsque vous jouerez au jeu, alors\n"
    .string "contactez moi sur discord pour que\n"
    .string "je pousse un correctif.\n"
    .string "Discord : .materia$"

gPikachuIntro_Text_Page3::
    .string "Cette traduction m'a pris énormément\n"
    .string "de temps et il est fort possible\n"
    .string "qu'il reste encore des coquilles à\n"
    .string "certains endroits…\n"
    .string "\n"
    .string "L'erreur est humaine donc soyez\n"
    .string "compréhensifs!$"

gOakSpeech_Text_WelcomeToTheWorld::
    .string "Bien le bonjour! Benvenue dans le\n"
    .string "monde incroyable des POKéMON\p"
    .string "Mon nom est CHEN!\p"
    .string "Les gens m'appellent amicalement\p"
    .string "le PROF. POKéMON!\p$"

gOakSpeech_Text_ThisWorld::
    .string "Ce monde…$"

gOakSpeech_Text_IsInhabitedFarAndWide::
    .string "… est peuplé de créatures\n"
    .string "appelées POKéMON!\p$"

gOakSpeech_Text_IStudyPokemon::
    .string "Pour certains, les POKéMON sont des\n"
    .string "animaux domestiques, pour d'autres,\p"
    .string "ils sont un moyen de combattre.\p"
    .string "Pour ma part…\p"
    .string "L'étude des POKéMON est ma\n"
    .string "profession\p.$"

gOakSpeech_Text_TellMeALittleAboutYourself::
    .string "Mais avant tout, parle-moi\n"
    .string "un peu de toi.\p$"

gOakSpeech_Text_YourNameWhatIsIt::
    .string "Comment t'appelles-tu?\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
    .string "D'accord…\n"
    .string "Donc tu t'appelles {PLAYER}.$"

gOakSpeech_Text_WhatWasHisName::
    .string "Voici mon petit-fils.\p"
    .string "Vous êtes rivaux depuis votre\n"
    .string "tendre enfance.\p"
    .string "… Heu…\n"
    .string "C'est quoi donc son nom déjà?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
    .string "Tu le connais, n'est-ce pas?$"

gOakSpeech_Text_ConfirmRivalName::
    .string "Euh, c'est bien {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
    .string "Mais oui, bien sûr que je m'en\n"
    .string "souviens, c'est {RIVAL}!\p$"

gOakSpeech_Text_LetsGo::
    .string "{PLAYER}!\p"
    .string "Ta quête des POKéMON est sur le\n"
    .string "point de commencer!\p"
    .string "Un tout nouveau monde de rêves,\n"
    .string "d'aventures et de POKéMON t'attend!\p"
    .string "Bonne chance!$"
