Text_ObtainedTheX::
	.string "{STR_VAR_2} obtenu !$"

Text_BagIsFull::
	.string "Le SAC est plein…$"

Text_PutItemAway::
	.string "{PLAYER} place {STR_VAR_2}\n"
	.string "dans {STR_VAR_3}.$"

Text_FoundOneItem::
	.string "{PLAYER} trouve {STR_VAR_2}!$"

Text_TooBadBagFull::
	.string "Dommage!\n"
	.string "Le SAC est plein…$"

Text_FoundXCoins::
	.string "{PLAYER} trouve\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

Text_PutCoinsAwayInCoinCase::
	.string "{PLAYER} place les JETONS dans\n"
	.string "la BOITE JETONS.$"

Text_CoinCaseIsFull::
	.string "Dommage!\n"
	.string "La BOITE JETONS est pleine…$"

Text_NothingToPutThemIn::
	.string "Dommage!\n"
	.string "Il n'y a rien à mettre à l'intérieur…$"

Text_FoundXItems::
	.string "{PLAYER} trouve\n"
	.string "{STR_VAR_1} {STR_VAR_2}(s)!$"

Text_ObtainedTheDecor::
	.string "{STR_VAR_2} obtenu !$"

Text_NoRoomForAnotherDecor::
	.string "Dommage! Il n'y a pas assez de\n"
	.string "place pour {STR_VAR_2}…$"

Text_DecorTransferredToPC::
	.string "{STR_VAR_2} a été transféré sur le\n"
	.string "PC.$"
