Text_MonSentToBoxInSomeonesPC::
    .string "{STR_VAR_2} a été transféré sur le\n"
    .string "PC de ???.\p"
    .string "Il a été placé dans la\n"
    .string "BOITE appelée “{STR_VAR_1}.”$"

Text_MonSentToBoxInBillsPC::
    .string "{STR_VAR_2} a été transféré sur le\n"
    .string "PC de LEO.\p"
    .string "Il a été placé dans la\n"
    .string "BOITE appelée “{STR_VAR_1}.”$"

Text_MonSentToBoxSomeonesBoxFull::
    .string "La BOITE “{STR_VAR_3}” du\n"
    .string "PC de ??? est pleine.\p"
    .string "{STR_VAR_2} a été placé dans la\n"
    .string "BOITE appelée “{STR_VAR_1}.”$"

Text_MonSentToBoxBillsBoxFull::
    .string "La BOITE “{STR_VAR_3}” du\n"
    .string "PC de LEO est pleine.\p"
    .string "{STR_VAR_2} a été placé dans la\n"
    .string "BOITE appelée “{STR_VAR_1}.”$"

Text_PlayerObtainedTheMon::
    .string "Et hop!\n"
    .string "{STR_VAR_1} est attrapé!$"

Text_NoMoreRoomForPokemon::
    .string "Il n'y a plus de place dans les BOITE!\p"
    .string "Toutes les boites sont pleine et\n"
    .string "ne peuvent recevoir aucun POKéMON!$"
