PokedexRating_Text_HowIsPokedexComingAlong::
	.string "CHEN: Je suis content de te revoir!\n"
	.string "Où en es-tu avec ton Pokédex?\p"
	.string "Voyons, voyons…$"

PokedexRating_Text_SeenXOwnedY::
	.string "Niveau POKéDEX:\p"
	.string "{STR_VAR_1} POKéMON vus et\n"
	.string "{STR_VAR_2} POKéMON pris.\p"
	.string "{FONT_NORMAL}Observation du PROF. CHEN:$"

PokedexRating_Text_LessThan10::
	.string "Tu ne vas pas assez dans les\p"
	.string "hautes herbes.\n"
	.string "Il t'en reste beaucoup à trouver!$"

PokedexRating_Text_LessThan20::
	.string "Tu es sur la bonne voie!\p"
	.string "Mon Assistant te donnera\n"
	.string "la CS Flash!$"

PokedexRating_Text_LessThan30::
	.string "Il te faut encore des\n"
	.string "POKéMON!\p"
	.string "Va en capturer d'autres!$"

PokedexRating_Text_LessThan40::
	.string "Très bien! Mon Assistant\n"
	.string "a un Cherch'Objet pour toi!$"

PokedexRating_Text_LessThan50::
	.string "C'est pas mal!\p"
	.string "Va voir mon Assistant quand\n"
	.string "tu en auras 50!$"

PokedexRating_Text_LessThan60::
	.string "Ah! Tu en as enfin 50!\p"
	.string "Mon Assistant te donnera\n"
	.string "un Multi Exp!$"

PokedexRating_Text_LessThan70::
	.string "Oh! C'est de mieux en mieux!$"

PokedexRating_Text_LessThan80::
	.string "Excellent! Va pêcher des\p"
	.string "POKéMON marins!$"

PokedexRating_Text_LessThan90::
	.string "Magnifique!\n"
	.string "T'es un vrai collectionneur!$"

PokedexRating_Text_LessThan100::
	.string "Mirobolant!\n"
	.string "Ça n'a pas dû être facile!$"

PokedexRating_Text_LessThan110::
	.string "Tu en as 100!\n"
	.string "Tu es vraiment très doué!$"

PokedexRating_Text_LessThan120::
	.string "Tu as même fait évoluer\n"
	.string "tes POKéMON! Génial!$"

PokedexRating_Text_LessThan130::
	.string "Parfait!\n"
	.string "Fais des échanges et tu en auras plus!$"

PokedexRating_Text_LessThan140::
	.string "Impressionnant!\n"
	.string "Tu es devenu un vrai pro!$"

PokedexRating_Text_LessThan150::
	.string "Chapeau bas!\n"
	.string "C'est toi le plus calé maintenant!$"

PokedexRating_Text_Complete::
	.string "Ton Pokédex est complet!\n"
	.string "Félicitations!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "Et ton POKéDEX NATIONAL est:\p"
	.string "{STR_VAR_1} POKéMON vus et\n"
	.string "{STR_VAR_2} POKéMON pris.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "J'ai hâte de te voir remplir le\n"
	.string "POKéDEX NATIONAL!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Enfin…\p"
	.string "Tu as rempli le POKéDEX!\n"
	.string "C'est magnifique!\p"
	.string "Merci! Tu as toute ma gratitude!$"

PokedexRating_Text_Wroooaaarrr::
	.string "Ouaaaaaah!!$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Merci, {PLAYER}!\n"
	.string "Sincèrement, Merci!\l"
	.string "Tu as fais de mon rêve une réalité!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "CHEN: Ah, bienvenue!\p"
	.string "Dis moi comment avance ton\n"
	.string "POKéDEX?\p"
	.string "Wahaha!\p"
	.string "En fait, je le sais déjà, mais\n"
	.string "j'aime le vérifier quand même!\p"
	.string "Regardons…$"
