@ The text here is a copy/paste from Hoenn's Safari Zone, and any unused text was left untranslated

SafariZone_Text_WouldYouLikeToExit::
	.string "Voulez-vous quitter le PARC SAFARI\n"
	.string "tout de suite?$"

SafariZone_Text_TimesUp::
	.string "Ding-dong!\p"
	.string "Le temps est écoulé!\p"
	.string "Votre partie de SAFARI est\n"
	.string "terminée.$"

SafariZone_Text_OutOfBalls::
	.string "Ding-dong!\p"
	.string "Vous n'avez plus de SAFARI BALLS.\p"
	.string "Votre partie de SAFARI est\n"
	.string "terminée.$"

SafariZone_Text_ExcuseMeYourPCBoxIsFull::
	.string "Excuse moi!\n"
	.string "Tes BOITES PC sont pleines!$"

