FourIsland_IcefallCave_Back_Text_LoreleiKeepHandsOffMons::
    .string "OLGA: Ne posez pas vos mains sur\n"
    .string "les POKéMON de cette grotte.\p"
    .string "Faites ce que je dis, ou vous\n"
    .string "allez avoir affaire à moi!$"

FourIsland_IcefallCave_Back_Text_ShutItLadyLeaveUsBe::
    .string "Pour qui tu te prends?\p"
    .string "Laisse-nous tranquilles et\n"
    .string "occupe-toi de tes affaires.$"

FourIsland_IcefallCave_Back_Text_LoreleiPlayerHelpMeKickPoachersOut::
    .string "OLGA: {PLAYER}?!\n"
    .string "Qu'est-ce que tu fais là?\p"
    .string "Non, on verra ça plus tard.\n"
    .string "J'ai bezoin de toi maintenant.\p"
    .string "Aide-moi à me débarasser de\n"
    .string "ces voleurs.\p"
    .string "Ils attrapent les POKéMON\n"
    .string "et les revendent après!\p"
    .string "A mon signal!\n"
    .string "Tu prends celui-là, ya?$"

FourIsland_IcefallCave_Back_Text_GruntIntro::
    .string "Qu-Quoi??\p"
    .string "Qui vous êtes pour nous dire ce\n"
    .string "qu'on doit faire avec nos POKéMON?$"

FourIsland_IcefallCave_Back_Text_GruntDefeat::
    .string "On avait pas prévu ça!$"

FourIsland_IcefallCave_Back_Text_LoreleiWhereHaveYouTakenMons::
    .string "OLGA: Humph.\n"
    .string "Espèce de misérable.\p"
    .string "Toi!\n"
    .string "Dis-moi!\p"
    .string "Où avez-vous emporté les\n"
    .string "POKéMON capturés?\p"
    .string "Dites-moi tout ou bien…$"

FourIsland_IcefallCave_Back_Text_NotTellingYouThat::
    .string "Ja-jamais!\n"
    .string "Je ne dirai rien!$"

FourIsland_IcefallCave_Back_Text_LoreleiWellDeepFreezeYou::
    .string "OLGA: Si vous ne parlez pas,\n"
    .string "nous allons vous congeler.\p"
    .string "Mon LOKHLASS est furieux de\n"
    .string "ce que vous avez fait.\p"
    .string "Go, LOKHLASS!\n"
    .string "LASER GLACE…$"

FourIsland_IcefallCave_Back_Text_OkayRocketWareHouseFiveIsland::
    .string "OK, OK, je vais parler!\p"
    .string "Les POKéMON sont dans l'ENTREPOT\n"
    .string "ROCKET sur l'ILE 5.\p"
    .string "Voilà, je l'ai dit!\n"
    .string "Laissez-nous maintenant!\p"
    .string "… Mais je suis sûr que vous\n"
    .string "arriverez jamais à l'ENTREPOT!\p"
    .string "Hehehehehe!$"

FourIsland_IcefallCave_Back_Text_ThankYouThisIsAwful::
    .string "{PLAYER}, merci beaucoup.\n"
    .string "Mais c'est vraiment affreux…\p"
    .string "Je suis née et j'ai grandi sur\n"
    .string "ces ILES.\p"
    .string "Je ne me doutais pas que ces\n"
    .string "bandits étaient ici…$"

