FourIsland_LoreleisHouse_Text_IfAnythingWereToHappenToIsland::
    .string "OLGA: Je n'arrête pas de penser\n"
    .string "à quelque choze.\p"
    .string "S'il devait arriver malheur sur mon\n"
    .string "île natale pendant que je suis\p"
    .string "à la LIGUE POKéMON…\p"
    .string "Je n'aurais aucun moyen de le\n"
    .string "savoir…\p"
    .string "Est-ce que ça fait de moi\n"
    .string "quelqu'un d'irresponsable?$"

FourIsland_LoreleisHouse_Text_IllReturnToLeagueInShortWhile::
    .string "OLGA: Alors tu as réussi à\n"
    .string "régler les problèmes?\p"
    .string "C'est fantastique!\p"
    .string "Ça veut dire que je peux repartir\n"
    .string "l'esprit tranquille.\p"
    .string "Merci…\p"
    .string "Je vais bientôt repartir pour la\n"
    .string "LIGUE POKéMON.$"

FourIsland_LoreleisHouse_Text_WillDoWhatICanHereAndNow::
    .string "Je ne sais pas ce qui peut se\n"
    .string "passer dans le futur, mais…\p"
    .string "Tant que je serai là, je\n"
    .string "protégerai cette île.$"

FourIsland_LoreleisHouse_Text_StuffedMonDollsGalore::
    .string "Il y a plein de poupées POKéMON.$"

