PokemonLeague_LoreleisRoom_Text_Intro::
    .string "Bienvenue à la LIGUE POKéMON!\p"
    .string "Je suis OLGA du CONSEIL 4!\p"
    .string "Je suis la maîtresse des\n"
    .string "POKéMON GLACE!\p"
    .string "Personne ne peut les battre…\p"
    .string "Tes POKéMON seront à ma merci\n"
    .string "une fois gelés!\p"
    .string "Ach! Ach! Ach!\n"
    .string "C'est parti!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_RematchIntro::
    .string "Bienvenue à la LIGUE POKéMON!\p"
    .string "Moi, OLGA du CONSEIL 4\n"
    .string "suis de retour!\p"
    .string "Tu sais que je suis la maîtresse\n"
    .string "des POKéMON GLACE!\p"
    .string "Personne ne peut les battre…\p"
    .string "Tes POKéMON seront à ma merci\n"
    .string "une fois gelés!\p"
    .string "Ach! Ach! Ach!\n"
    .string "C'est reparti!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_Defeat::
    .string "…Ça devait pas se passer comme ça!$"

PokemonLeague_LoreleisRoom_Text_PostBattle::
    .string "Tu sais te battre.\n"
    .string "C'est bien.\p"
    .string "Mais la LIGUE POKéMON te réserve\n"
    .string "d'autres surprises!$"

