Text_MetronomeTeach::
    .string "Tik-Tak-Tik-Tak!\n"
    .string "Je veux t'apprendre une super\l"
    .string "capacité.\p"
    .string "Enseigne-la à un de tes POKéMON\n"
    .string "et regarde bien le résultat!\p"
    .string "Cette capacité s'appelle\n"
    .string "METRONOME. Ça te tente?$"

Text_MetronomeDeclined::
    .string "Crois-moi, c'est super marrant!$"

Text_MetronomeWhichMon::
    .string "OK, l'apprendre à quel POKéMON?$"

Text_MetronomeTaught::
    .string "Tik-Tak-Tik-Tak!\n"
    .string "C'est le bruit du METRONOME!\p"
    .string "Cette technique modifie\n"
    .string "le cerveau d'un POKéMON et lui\p"
    .string "fait utiliser des capacités qu'il\n"
    .string "ne connaissait même pas!$"

Text_MetronomeReteach::
    .string "Tik-Tak-Tik-Tak!\n"
    .string "Le METRONOME ne s'arrête jamais!\p"
    .string "Je peux te l'apprendre une\n"
    .string "nouvelle fois pour ¥5000.$"

Text_MetronomeReteach2::
    .string "Tik-Tak-Tik-Tak!\n"
    .string "Tu veux apprendre METRONOME?$"

Text_MetronomeNotEnoughMoney::
    .string "Tik-Tak-Tik-Tak!\n"
    .string "Le temps c'est de l'argent\n"
    .string "et tu n'en a pas assez!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_HaveYouAFossilForMe::
    .string "Salut!\p"
    .string "Je suis un scientifique très\n"
    .string "sérieux!\p"
    .string "J'étudie les fossiles anciens\n"
    .string "de POKéMON!\p"
    .string "Dis-moi. Tu n'aurais pas un\n"
    .string "fossile pour moi?$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoIsTooBad::
    .string "Non?\n"
    .string "C'est bien dommage!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_FossilMonBackToLife::
    .string "Tu es en retard.\n"
    .string "Où étais-tu?\p"
    .string "Ton fossile est VIVANT!\n"
    .string "On dirait un {STR_VAR_1}!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ReceivedMonFromDoctor::
    .string "{PLAYER} reçoit\n"
    .string "{STR_VAR_1}!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ThatFossilIsOfMonMakeItLiveAgain::
    .string "Oh!\n"
    .string "C'est un {STR_VAR_2}.\p"
    .string "C'est un fossile de {STR_VAR_1},\n"
    .string "un POKéMON qui a disparu!\p"
    .string "Ma machine à réanimer va faire\n"
    .string "revivre cet ancien POKéMON!$"

@ TODO: Resolve text dump error below?
CinnabarIsland_PokemonLab_ExperimentRoom_Text_HandedFossilToWeirdDoctor::
    .string "Allez!\n"
    .string "Dépêche-toi et donne-moi ça!\p"
    .string "{FONT_NORMAL}{PLAYER} donne le\n"
    .string "{STR_VAR_2}.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalk::
    .string "Ça va prendre du temps!\p"
    .string "Va te promener pendant que je\n"
    .string "travaille!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_YouComeAgain::
    .string "Argayahha!\n"
    .string "Tu reviendras!$"

