Route21_North_Text_RonaldIntro::
    .string "Tu veux savoir s'il y a des\n"
    .string "poissons ici?$"

Route21_North_Text_RonaldDefeat::
	.string "Paf!$"

Route21_North_Text_RonaldPostBattle::
	.string "Y'a comme un manque de poisson!$"

Route21_North_Text_WadeIntro::
    .string "J'ai eu une bonne prise!\n"
    .string "Tu veux tester?$"

Route21_North_Text_WadeDefeat::
    .string "Zut!\n"
    .string "Encore un MAGICARPE!$"

Route21_North_Text_WadePostBattle::
    .string "Je ne pêche que\n"
    .string "des MAGICARPE!$"

Route21_North_Text_SpencerIntro::
	.string "Ah, je suis revigoré par l'écume.$"

Route21_North_Text_SpencerDefeat::
	.string "Ayah!$"

Route21_North_Text_SpencerPostBattle::
    .string "J'adore la mer mais j'ai rien\n"
    .string "contre la montagne!$"
