SevenIsland_House_Room1_Text_OnlyEnjoymentWatchingBattles::
    .string "Je sais que c'est dur à croire,\n"
    .string "mais quand j'étais plus jeune,\p"
    .string "j'adorais être sur les routes pour\n"
    .string "affronter tous les DRESSEURS\p"
    .string "que je pouvais rencontrer.\p"
    .string "Maintenant, ma seule source de\n"
    .string "distraction est de me rappeler\p"
    .string "du passé en regardant des\n"
    .string "combats.$"
    .string "Attends, ces BADGES…\n"
    .string "Tu as battu les CHAMPION de KANTO?\l"
    .string "Tu es si fort que ça ?\p"
    .string "Tu as du rencontrer beaucoup\n"
    .string "de DRESSEURS redoutables.\p"
    .string "Peux tu rester un peu avec moi\n"
    .string "pour me raconter ton périple?$"

SevenIsland_House_Room1_Text_ShowFameChecker::
    .string "Lui montrer le MEMORYDEX?$"

SevenIsland_House_Room1_Text_NoShowFameChecker::
    .string "Je vois…\n"
    .string "Je te souhaite bon voyage…$"

SevenIsland_House_Room1_Text_ManyTrainersWhich::
    .string "Il y a beaucoup de DRESSEURS là dedans.\n"
    .string "De qui veux tu me parler?$"

SevenIsland_House_Room1_Text_NotFullFamecheckerForPerson::
    .string "Hmm… {STR_VAR_1}…?\p"
    .string "Il n'y a pas assez d'informations sur\n"
    .string "{STR_VAR_1} pour savoir comment\l"
    .string "{STR_VAR_2} combat.\p"
    .string "Reviens me voir quand tu auras\n"
    .string "plus d'informations à son sujet.$"

SevenIsland_House_Room1_Text_FullFamecheckerForPerson::
    .string "…!\p"
    .string "Oui, {STR_VAR_1} est vraiment le\n"
    .string "genre de DRESSEUR que j'aime voir!$"

SevenIsland_House_Room1_Text_FirstFullFamecheckerPerson::
    .string "Je vais t'avouer une chose, il\n"
    .string "y a une salle cachée dans la cave.\p"
    .string "Je me suis entraînée à l'époque\n"
    .string "à l'intérieur avec d'autres DRESSEURS\p"
    .string "Je vais inviter {STR_VAR_1} et\n"
    .string "réouvrir la salle.\p"
    .string "Comme ça tu pourras t'entraîner!$"

SevenIsland_House_Room1_Text_CallSpearow::
    .string "PIAFABEC!\n"
    .string "Viens ici s'il te plait!$"

SevenIsland_House_Room1_Text_DeliverToLeader::
    .string "Envoie cette invitation à {STR_VAR_1}.\n"
    .string "Il se trouve à {STR_VAR_3}!$"

SevenIsland_House_Room1_Text_FirstTakeTime::
    .string "Il va se passer du temps avant\n"
    .string "le retour de PIAFABEC.\p"
    .string "Tu n'as pas besoin d'attendre\n"
    .string "ici. Reviens plus tard.\p"
    .string "Pendant ce temps je vais\n"
    .string "rénover la cave.$"

SevenIsland_House_Room1_Text_TakeTime::
    .string "Il va se passer du temps avant\n"
    .string "le retour de PIAFABEC.\p"
    .string "Tu n'as pas besoin d'attendre\n"
    .string "ici. Reviens plus tard.\p$"

SevenIsland_House_Room1_Text_AlreadyShownPerson::
    .string "{STR_VAR_1}?\p"
    .string "J'ai déjà envoyé une invitation à\n"
    .string "{STR_VAR_1}.$"

SevenIsland_House_Room1_Text_SpearowNotBackYet::
    .string "PIAFABEC n'est pas encore rentré.\n"
    .string "Nous allons devoir attendre encore\l"
    .string "un peu pour avoir une réponse.$"

SevenIsland_House_Room1_Text_InviteBasementOpen::
    .string "Je vais écrire une lettre à\n"
    .string "{STR_VAR_1} et l'envoyer de suite!$"

SevenIsland_House_Room1_Text_HeString::
    .string "il$"

SevenIsland_House_Room1_Text_SheString::
    .string "elle$"

SevenIsland_House_Room1_Text_Spearow::
    .string "PIAFABEC: Piaf!$"

SevenIsland_House_Room1_Text_SlightBreezeAroundBox::
    .string "Il y a un courant d'air derrière\n"
    .string "les cartons.$"

SevenIsland_House_Room1_Text_OldWomanNoVisitors::
    .string "Bonjour, {PLAYER}.\n"
    .string "Tu viens pour t'entraîner?\p"
    .string "Pour le moment personne n'est\n"
    .string "arrivé, mais si tu connais d'autres\l"
    .string "DRESSEURS costauds alors j'aimerai\l"
    .string "bien en entendre parler!$"

SevenIsland_House_Room1_Text_OldWomanOneVisitor::
    .string "Bonjour, {PLAYER}.\n"
    .string "Tu viens pour t'entraîner?\p"
    .string "{STR_VAR_1} est arrivé, il se\n"
    .string "trouve dans la cave.\p"
    .string "Ou alors tu connais des DRESSEURS\n"
    .string "encore plus forts?$"

SevenIsland_House_Room1_Text_OldWomanMultiVisitors::
    .string "Bonjour, {PLAYER}.\n"
    .string "Tu viens pour t'entraîner?\p"
    .string "{STR_VAR_2} DRESSEURS se trouvent\n"
    .string "dans la cave.\p"
    .string "Ou alors tu connais des DRESSEURS\n"
    .string "encore plus forts?$"

SevenIsland_House_Room1_Text_OldWomanToldAllNoVisitors::
    .string "Bonjour, {PLAYER}.\n"
    .string "Tu viens pour t'entraîner?\p"
    .string "Pour le moment personne n'est\n"
    .string "arrivé. Mais malgré cela\p"
    .string "je suis comblée de joie avec\n"
    .string "les combats que j'ai vu!$"

SevenIsland_House_Room1_Text_OldWomanToldAllOneVisitor::
    .string "Bonjour, {PLAYER}.\n"
    .string "Tu viens pour t'entraîner?\p"
    .string "{STR_VAR_1} est arrivé, il se\n"
    .string "trouve dans la cave.\p"
    .string "Je ne pourrais jamais te\n"
    .string "remercier assez pour tout le\l"
    .string "bonheur que tu apportes dans ma vie.$"

SevenIsland_House_Room1_Text_OldWomanToldAllMultiVisitors::
    .string "Bonjour, {PLAYER}.\n"
    .string "Tu viens pour t'entraîner?\p"
    .string "{STR_VAR_2} DRESSEURS se trouvent\n"
    .string "dans la cave.\p"
    .string "Je ne pourrais jamais te\n"
    .string "remercier assez pour tout le\l"
    .string "bonheur que tu apportes dans ma vie.$"

SevenIsland_House_Room1_Text_NoShowFameChecker2::
    .string "Ok, {PLAYER}, dis moi quand\n"
    .string "tu auras appris de nouvelles choses.$"

SevenIsland_House_Room1_Text_Two::
    .string "Deux$"

SevenIsland_House_Room1_Text_Three::
    .string "Trois$"

SevenIsland_House_Room1_Text_Four::
    .string "Quatre$"

SevenIsland_House_Room1_Text_Five::
    .string "Cinq$"

SevenIsland_House_Room1_Text_Six::
    .string "Six$"

SevenIsland_House_Room1_Text_Seven::
    .string "Sept$"
