Route22_Text_EarlyRivalIntro::
    .string "{RIVAL}: Hé! {PLAYER}!\p"
    .string "Tu vas à la LIGUE POKéMON?\n"
    .string "Laisse tomber!\p"
    .string "T'es bien trop minable. En plus il\n"
    .string "te faut des BADGES!\p"
    .string "Les gardes ne te laisseront\n"
    .string "jamais passer!\p"
    .string "Au fait, ça se passe comment\n"
    .string "l'entraînement de tes POKéMON?$"

Route22_Text_EarlyRivalDefeat::
    .string "Haha! C'est la chance des\n"
    .string "débutants!$"

Route22_Text_EarlyRivalPostBattle::
    .string "Il paraît qu'il y a des super\n"
    .string "DRESSEURS dans la LIGUE POKéMON!\p"
    .string "Je dois trouver un moyen de\n"
    .string "les battre!\p"
    .string "Tu devrais t'y mettre sérieusement\n"
    .string "si tu veux les battre!$"

Route22_Text_LateRivalIntro::
    .string "{RIVAL}: Tiens? {PLAYER}! Quelle\n"
    .string "surprise, tu es là aussi?!\p"
    .string "Alors comme ça tu vas à la LIGUE?\n"
    .string "Tu as tous les BADGES aussi?\l"
    .string "C'est bien!\p"
    .string "Bon, je vais m'occuper vite\n"
    .string "fait de toi!\p"
    .string "Ça me fera un échauffement\n"
    .string "avant la LIGUE POKéMON!\p"
    .string "Allez, viens te battre!$"

Route22_Text_LateRivalDefeat::
    .string "Quoi!?\p"
    .string "Je pensais juste à autre chose!$"

Route22_Text_LateRivalPostBattle::
    .string "C'était un bon échauffement!\n"
    .string "J'suis prêt pour la LIGUE POKéMON!\p"
    .string "{PLAYER}, faut vraiment que tu\n"
    .string "t'entraînes plus!\p"
    .string "Mais je crois que tu commences à\n"
    .string "le savoir. Tchao!$"

Route22_Text_LeagueGateSign::
    .string "LIGUE POKéMON\n"
    .string "Entrée principale$"

