BattleTower_BattleRoom_Text_19ACDC::
	.string "Nous allons soigner tes POKéMON.$"

BattleTower_BattleRoom_Text_19AD09::
	.string "Tu vas affronter l'adversaire N.{STR_VAR_1}.\n"
	.string "Are you ready?$"

BattleTower_BattleRoom_Text_19AD3C::
	.string "Voulez-vous sauvegarder et quitter\n"
	.string "le jeu?$"

BattleTower_BattleRoom_Text_19AD66::
	.string "Voulez-vous abandonner votre\n"
	.string "challenge?$"

BattleTower_BattleRoom_Text_1C6CE1::
	.string "SAUVEGARDE EN COURS…\n"
	.string "N'ETEIGNEZ PAS LA CONSOLE.$"

BattleTower_BattleRoom_Text_1C6D05::
	.string "{PLAYER} a sauvegardé la partie.$"