BattleTower_Lobby_Text_199F2C::
    .string "Bienvenue dans la TOUR DE COMBAT!\p"
    .string "Veuillez vous inscrire pour accéder à\n"
    .string "une SALLE DE COMBAT.$"

BattleTower_Lobby_Text_199F79::
    .string "Voulez-vous relever le défi d'une\n"
    .string "SALLE DE COMBAT?$"

BattleTower_Lobby_Text_199FA9::
    .string "Nous attendrons votre prochain défi\n"
    .string "avec impatience.$"

BattleTower_Lobby_Text_199FDA::
    .string "Avant d'accéder à une SALLE DE COMBAT,\n"
    .string "votre partie doit être sauvegardée. OK?$"

BattleTower_Lobby_Text_19A024::
    .string "Il y a deux types de SALLES DE COMBAT:\n"
    .string "niveau 50 et sans limites.\p"
    .string "Quel défi voulez-vous relever?$"

BattleTower_Lobby_Text_19A07B::
    .string "Veuillez choisir les POKéMON que vous\n"
    .string "souhaitez inscrire.$"

BattleTower_Lobby_Text_19A0A8::
	.string "Je vais vous mener à la SALLE DE COMBAT.$"

BattleTower_Lobby_Text_19A0D1::
    .string "La TOUR DE COMBAT est un bâtiment\n"
    .string "conçu pour les combats de POKéMON.\p"
    .string "Il y a de nombreuses SALLES DE COMBAT\n"
    .string "dans la TOUR.\p"
    .string "Dans chaque SALLE DE COMBAT, sept\n"
    .string "DRESSEURS sont prêts à vous défier.\p"
    .string "Battez-les tous les sept et vous\n"
    .string "recevrez un prix fabuleux.\p"
    .string "Vous pouvez aussi faire une pause\n"
    .string "et sauvegarder pendant un défi.\p"
    .string "Assurez-vous de bien sauvegarder, ou\n"
    .string "vous ne pourrez pas reprendre le défi.$"

BattleTower_Lobby_Text_19A249::
    .string "Je regrette!\p"
    .string "Vous n'avez pas trois POKéMON\n"
    .string "aptes à participer.\p"
    .string "Il vous faut trois POKéMON différents\n"
    .string "de niveau 50 ou moins pour participer.\p"
    .string "Ils doivent aussi tenir des objets\n"
    .string "différents.\p"
    .string "Les OEUFS{STR_VAR_1} inaptes\n"
    .string "au combat.\p"
    .string "Revenez me voir quand vous aurez\n"
    .string "ce qu'il faut.$"

BattleTower_Lobby_Text_19A32D::
    .string "Je regrette!\p"
    .string "Vous n'avez pas trois POKéMON\n"
    .string "aptes à participer.\p"
    .string "Il vous faut trois POKéMON différents\n"
    .string "pour participer.\p"
    .string "Ils doivent aussi tenir des objets\n"
    .string "différents.\p"
    .string "Les OEUFS{STR_VAR_1} inaptes\n"
    .string "au combat.\p"
    .string "Revenez me voir quand vous aurez\n"
    .string "ce qu'il faut.$"

BattleTower_Lobby_Text_19A3FD::
	.string "Excusez-moi!\p"
	.string "Vous n'avez pas sauvegardé\n"
	.string "lors de votre dernière participation.\p"
	.string "Par conséquent vous avez été\n"
	.string "disqualifié. Désolé!$"

BattleTower_Lobby_Text_19A487::
    .string "Félicitations!\n"
    .string "Vous avez battu les sept DRESSEURS!\p$"

BattleTower_Lobby_Text_19A4BB::
    .string "Pour avoir battu sept DRESSEURS de\n"
    .string "suite, vous avez droit à un lot fabuleux!\p$"

BattleTower_Lobby_Text_19A506::
    .string "{PLAYER} reçoit {STR_VAR_1}\n"
    .string "en récompense.$"

BattleTower_Lobby_Text_19A520::
    .string "Oh, votre SAC est plein.\p"
    .string "Veuillez faire de la place dans votre SAC\n"
    .string "et revenez ensuite me voir.$"

BattleTower_Lobby_Text_19A571::
	.string "Merci d'être venu!\p"
	.string "$"

BattleTower_Lobby_Text_19A589::
    .string "Votre record va être sauvegardé.\n"
    .string "Veuillez patienter.$"

BattleTower_Lobby_Text_19A5B1::
	.string "Nous vous attendions!\p"
	.string "$"

BattleTower_Lobby_Text_19A5CE::
	.string "avant d'entrer dans la SALLE DE COMBAT,\n"
	.string "votre partie va être sauvegardée.\lVeuillez patienter.$"

BattleTower_Lobby_Text_19A617::
	.string "Vous allez enfin affronter le\n"
	.string "DRESSEUR N.50.\p"
	.string "A partir de maintenant, a chaque\n"
	.string "que vous completez une série, vos\l"
	.string "POKéMON recevront un\lRUBAN spécial.\p"
	.string "Bonne chance!$"

BattleTower_Lobby_Text_19A6BE::
	.string "Voici des RUBANS pour avoir battu\n"
    .string "sept DRESSEURS costauds à la suite.\p"
    .string "{COLOR DARK_GRAY}{PLAYER} reçoit des RUBANS!$"

BattleTower_Lobby_Text_19A719::
	.string "{COLOR DARK_GRAY}{PLAYER} met les RUBANS sur le\n"
    .string "POKéMON ayant relevé le défi.$"

BattleTower_Lobby_Text_19A747::
    .string "Salut, salut!\n"
    .string "D'où viens-tu, DRESSEUR?\p"
    .string "…\p"
    .string "KANTO? BOURG PALETTE?\n"
    .string "C'est très loin d'ici!$"

BattleTower_Lobby_Text_19A8AE::
    .string "Le nombre de matchs gagnés\n"
    .string "successivement est enregistré.\p"
    .string "Ce résultat est ensuite affiché au\n"
    .string "guichet d'inscription.$"

BattleTower_Lobby_Text_19A946::
    .string "Une fois dans la TOUR DE COMBAT,\n"
    .string "tu ne peux pas sortir avant de\p"
    .string "perdre ou de battre sept\n"
    .string "DRESSEURS à la suite.\p"
    .string "T'as intérêt à te motiver sérieusement\n"
    .string "avant de décider de relever le défi.$"

BattleTower_Lobby_Text_Scott28Wins::
	.string "SCOTT: C'est du génie à l'état pur!\n"
    .string "Du génie super génial!\p"
    .string "Tu te rends compte de ton exploit?\n"
    .string "Tu as battu 28 DRESSEURS à la suite!\p"
    .string "Oui, du génie génialissimement génial!\p"
    .string "En tant que PROPRIETAIRE  de la TOUR\n"
    .string "DE COMBAT, je vais t'offrir un souvenir!$"

BattleTower_Lobby_Text_ScottExplainAuroraTicket::
	.string "Apportes ce ticket à ton ami\n"
	.string "du PORT DE CARMIN SUR MER.\p"
	.string "Il pourra t'emmener sur une\n"
	.string "petite ILE au sud de l'ILE 6.\p"
	.string "Il y a une drôle de pierre\n"
	.string "Là-bas.\p"
	.string "C'est très sympa et c'est une\n"
	.string "bonne destination de vacances!$"

BattleTower_Lobby_Text_Scott56Wins::
	.string "Hahahaha! C'est du génie à l'état pur!\n"
    .string "Du génie super génial!\p"
    .string "Tu te rends compte de ton exploit?\n"
    .string "Tu as battu 56 DRESSEURS à la suite!\p"
    .string "Oui, du génie génialissimement génial!\p"
    .string "En tant que PROPRIETAIRE  de la TOUR\n"
    .string "DE COMBAT, je vais t'offrir un souvenir!$"

BattleTower_Lobby_Text_ScottExplainEonTicket::
	.string "Apportes ce ticket à ton ami\n"
	.string "du PORT DE CARMIN SUR MER.\p"
	.string "Il pourra t'emmener sur une\n"
	.string "ILE non loin d'ici.\p"
	.string "Il y a un joli petit bosquet là-bas,\n"
	.string "parfait pour te reposer après\l"
	.string "les entraînements.$"

BattleTower_Lobby_Text_ScottGaveAuroraTicket::
	.string "Je vais continuer de suivre tes\n"
	.string "exploits à partir de maintenant!$"

BattleTower_Lobby_Text_ScottGaveEonTicket::
	.string "Cette TOUR DE COMBAT a été un\n"
	.string "grand succès mais…\p"
	.string "Il faudrait peut-être pousser\n"
	.string "ce projet encore plus loin…$"
