LavenderTown_PokemonCenter_1F_Text_HearMrFujiNotFromAroundHere::
    .string "Je viens d'emménager ici.\p"
    .string "Il paraît que MR. FUJI n'est\n"
    .string "pas non plus du coin.$"

LavenderTown_VolunteerPokemonHouse_Text_WhereDidMrFujiGo::
    .string "Ce sacré MR. FUJI n'est pas là.\n"
    .string "Où est-il?$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiWasPrayingForCubonesMother::
    .string "MR. FUJI a prié pour le repos de\n"
    .string "la mère d'OSSELAIT.$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiLooksAfterOrphanedMons::
    .string "Voici la maison de MR. FUJI.\p"
    .string "C'est vraiment un chic type!\p"
    .string "Il est à la recherche des POKéMON\n"
    .string "orphelins et abandonnés!$"

LavenderTown_VolunteerPokemonHouse_Text_MonsNiceToHug::
    .string "C'est si doux! Faire un câlin à un\n"
    .string "POKéMON, c'est chou!$"

LavenderTown_VolunteerPokemonHouse_Text_Nidorino::
    .string "NIDORINO: Nido!$"

LavenderTown_VolunteerPokemonHouse_Text_Psyduck::
    .string "PSYKOKWAK: Kwak!$"

LavenderTown_VolunteerPokemonHouse_Text_IdLikeYouToHaveThis::
    .string "MR. FUJI: {PLAYER}.\p"
    .string "Ta quête pour compléter ton\n"
    .string "POKéDEX échouera si tu n'aimes pas\l"
    .string "tes POKéMON.\p"
    .string "Je crois que ceci te sera utile.$"

LavenderTown_VolunteerPokemonHouse_Text_ReceivedPokeFluteFromMrFuji::
    .string "{PLAYER} obtient la\n"
    .string "POKéFLUTE!$"

LavenderTown_VolunteerPokemonHouse_Text_ExplainPokeFlute::
    .string "En jouant de la POKéFLUTE, les\n"
    .string "POKéMON endormis se réveilleront.\p"
    .string "Elle marche sur tous les POKéMON.$"

LavenderTown_VolunteerPokemonHouse_Text_MustMakeRoomForThis::
    .string "Ton inventaire est plein!$"

LavenderTown_VolunteerPokemonHouse_Text_HasPokeFluteHelpedYou::
    .string "MR. FUJI: Ma FLUTE t'a été utile?$"

LavenderTown_VolunteerPokemonHouse_Text_GrandPrizeDrawingClipped::
    .string "Grand concours de dessin du\n"
    .string "magazine des fans de POKéMON!\p"
    .string "Le formulaire d'inscription est…\p"
    .string "Il a disparu! Quelqu'un a déjà dû\n"
    .string "l'utiliser.$"

LavenderTown_VolunteerPokemonHouse_Text_PokemonMagazinesLineShelf::
    .string "Des magazines POKéMON!\p"
    .string "Des cahiers POKéMON!\p"
    .string "Des dessins POKéMON!$"

LavenderTown_VolunteerPokemonHouse_Text_FindFarawayIsland::
    .string "MR. FUJI: As-tu trouvé l'ILE\n"
    .string "indiquée sur ma VIEILLE CARTE?$"

LavenderTown_VolunteerPokemonHouse_Text_FoundMew::
    .string "MR. FUJI: {PLAYER}!\p"
    .string "Est-ce que ma VIEILLE CARTE\n"
    .string "a été utile?\p"
    .string "As-tu trouvé le POKéMON?$"

LavenderTown_VolunteerPokemonHouse_Text_DefeatedMew::
    .string "Ah, ce pauvre POKéMON s'est\n"
    .string "enfuit lorsqu'il t'as vu?\p"
    .string "Peut-être que certaines erreurs\n"
    .string "ne peuvent être réparées…\p"
    .string "Je dois quand même vous remercier\n"
    .string "pour votre aide, {PLAYER}.\p"
    .string "Peut-être que ce POKéMON\n"
    .string "réapparaîtra un jour…$"

LavenderTown_VolunteerPokemonHouse_Text_CaughtMew::
    .string "Vous avez pu vous lier\n"
    .string "d'amitié avec lui? Même\p"
    .string "après tout ce qu'il a enduré?\p"
    .string "Merci, {PLAYER}!\p"
    .string "Tu as apaisé ma conscience et\n"
    .string "calmé ce pauvre POKéMON.\p"
    .string "Je suis certains que vous\n"
    .string "deviendrez encore plus proches\p"
    .string "avec le temps.$"

LavenderTown_VolunteerPokemonHouse_Text_AnsweredNo::
    .string "La VIEILLE CARTE indique\n"
    .string "comment se rendre sur cette ILE.\p"
    .string "Un marin devrait être capable de\n"
    .string "la lire et de t'y emmener.\p"
    .string "Tu connais quelqu'un avec un\n"
    .string "bateau {PLAYER}?$"

LavenderTown_VolunteerPokemonHouse_Text_NotEncounteredMew::
    .string "Tu n'as donc pas encore\n"
    .string "trouvé le POKéMON.\p"
    .string "Si je me souviens bien, il adore\n"
    .string "jouer dans les hautes herbes.$"

LavenderTown_VolunteerPokemonHouse_Text_HowAreYouAndMew::
    .string "MR. FUJI: {PLAYER}! Bienvenue!\n"
    .string "Comment allez-vous, mew et toi?$"

