SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMale::
    .string "{PLAYER}: Salut!\n"
    .string "Tu aimes les POKéMON?\p"
    .string "{PLAYER}: Heu, non\n"
    .string "Je demandais juste!\p"
    .string "{PLAYER}: Hein?\n"
    .string "T'es bizarre toi!\p"
    .string "COPIEUSE: Hmm?\n"
    .string "Arrêter de mimer?\p"
    .string "Mais je ne sais faire que ça!$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemale::
    .string "{PLAYER}: Salut! Tu dois aimer\n"
    .string "les POKéMON, non?\p"
    .string "{PLAYER}: Heu, non\n"
    .string "Je demandais juste!\p"
    .string "{PLAYER}: Hein?\n"
    .string "T'es bizarre toi!\p"
    .string "COPIEUSE: Hmm?\n"
    .string "Arrêter de mimer?\p"
    .string "Mais je ne sais faire que ça!$"

Text_MimicTeach::
    .string "Whaaaaaa!\n"
    .string "Une POKéPOUPEE!\p"
    .string "C'est pour moi?\n"
    .string "Merci!\p"
    .string "Je peux t'apprendre COPIE!$"

Text_MimicDeclined::
    .string "T'aimes pas COPIE?$"

Text_MimicWhichMon::
    .string "Moi aussi j'adore! Alors, qui\n"
    .string "va l'apprendre?$"

Text_MimicTaughtMale::
    .string "{PLAYER}: Salut!\n"
    .string "Merci pour tout à l'heure!\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Ça te fait rire d'imiter\n"
    .string "tout mes mouvements?\p"
    .string "COPYCAT: Clairement!\n"
    .string "C'est un délice!$"

Text_MimicTaughtFemale::
    .string "{PLAYER}: Salut!\n"
    .string "Merci pour tout à l'heure!\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Ça te fait rire d'imiter\n"
    .string "tout mes mouvements?\p"
    .string "COPYCAT: Clairement!\n"
    .string "C'est un délice!$"

Text_MimicReteach::
    .string "{PLAYER}: Salut! Tu peux nous\n"
    .string "apprendre COPIE encore une fois?\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Ça te fait rire d'imiter\n"
    .string "tout mes mouvements?\p"
    .string "COPYCAT: Clairement!\n"
    .string "C'est un délice!\p"
    .string "Je peux te l'apprendre pour ¥5000\n"
    .string "C'est pour mes POKéPOUPEE!$"

Text_MimicReteach2::
    .string "C'est ok?\n"
    .string "Je dois t'apprendre COPIE?$"

Text_MimicNotEnoughMoney::
    .string "{PLAYER}: ¥5000?\n"
    .string "Mais une POKéPOUPEE coûte ¥1000!\p"
    .string "Je n'ai pas assez d'argent\n"
    .string "pour le moment…\p"
    .string "COPYCAT: J'en veux 5!\n"
    .string "Donc j'ai besoin de ¥5000!\p"
    .string "Je t'apprendrais COPIE quand\n"
    .string "tu auras assez d'argent!$"

Text_MimicTaughtMale2::
    .string "{PLAYER}: Ok!\n"
    .string "Merci bien!\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Ça te fait rire d'imiter\n"
    .string "tout mes mouvements?\p"
    .string "COPYCAT: Clairement!\n"
    .string "C'est un délice!$"

Text_MimicTaughtFemale2::
    .string "{PLAYER}: Ok!\n"
    .string "Merci bien!\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Ça te fait rire d'imiter\n"
    .string "tout mes mouvements?\p"
    .string "COPYCAT: Clairement!\n"
    .string "C'est un délice!$"

SaffronCity_CopycatsHouse_2F_Text_Doduo::
    .string "DODUO: Doduuu!\p"
    .string "JOLI MIROIR, DIS-MOI QUI EST\n"
    .string "LA PLUS BELLE!$"

SaffronCity_CopycatsHouse_2F_Text_RareMonOnlyDoll::
    .string "Ça, un POKéMON rare? Tu t'moques\n"
    .string "de moi! C'est rien qu'une poupée!$"

SaffronCity_CopycatsHouse_2F_Text_MarioWearingABucket::
    .string "Un plombier? Mais…\n"
    .string "Ça a l'air sympa.$"

SaffronCity_CopycatsHouse_2F_Text_MySecrets::
    .string "…\p"
    .string "Mes secrets!\p"
    .string "Mon boulot: je mime!\n"
    .string "Ma passion: les poupées!\l"
    .string "Mon POKéMON préféré: MELOFEE!$"
