
BattleTower_Outside_Text_199C6F::
	.string "TOUR DE COMBAT\n"
    .string "“Soyez victorieux et devenez le\l"
    .string "meilleur DRESSEUR!“$"

BattleTower_Outside_Text_199CA4::
    .string "Voici la TOUR DE COMBAT.\p"
    .string "Les DRESSEURS y amènent leurs\n"
    .string "meilleurs POKéMON pour participer\l"
    .string "à des matchs éliminatoires.$"

BattleTower_Outside_Text_199E9C::
    .string "Je ne partirai pas avant d'avoir\n"
    .string "battu 35 DRESSEURS à la suite!$"

BattleTower_Outside_Text_199ED4::
    .string "Bon sang, les DRESSEURS semblent\n"
    .string "forts.\p"
    .string "Je ne suis pas assez bon pour y\n"
    .string "aller…$"
