
BattleTower_Outside_Text_199C6F::
	.string "TOUR DE COMBAT\n"
    .string "“Soyez victorieux et devenez le\l"
    .string "meilleur DRESSEUR!“$"

BattleTower_Outside_Text_199CA4::
    .string "Voici la TOUR DE COMBAT.\p"
    .string "Les DRESSEURS y amènent leurs meilleurs\n"
    .string "POKéMON pour participer à des matchs\l"
    .string "éliminatoires.$"

BattleTower_Outside_Text_199E9C::
    .string "Je ne partirai pas avant d'avoir battu\n"
    .string "35 DRESSEURS à la suite!$"

BattleTower_Outside_Text_199ED4::
    .string "Bon sang, les DRESSEURS semblent forts.\n"
    .string "Je ne suis pas assez bon pour y aller…$"
