@ The 5 texts below are supposed to be in FourIsland_House1
Text_BodySlamTeach::
    .string "Prêts?\n"
    .string "Go!\p"
    .string "On fait un concours de PLAQUAGE.\p"
    .string "Si tu veux essayer, tu vas te faire\n"
    .string "écraser comme un insecte!\p"
    .string "Et si j'apprenais plutôt cette\n"
    .string "capacité à un de tes POKéMON?$"

Text_BodySlamDeclined::
    .string "Whoua!$"

Text_BodySlamWhichMon::
    .string "A quel POKéMON vais-je\n"
    .string "enseigner PLAQUAGE?$"

Text_BodySlamTaught::
    .string "Allez!\n"
    .string "Go!$"

Text_BodySlamReteach::
    .string "T'en veux encore?\n"
    .string "Paf!\p"
    .string "On fait encore un concours de\n"
    .string "PLAQUAGE.\p"
    .string "Tu veux que j'apprenne PLAQUAGE\n"
    .string "à ton POKéMON pour ¥5000?$"

Text_BodySlamReteach2::
    .string "Tu veux que j'apprenne\n"
    .string "PLAQUAGE à un POKéMON?$"

Text_BodySlamNotEnoughMoney::
    .string "Paf? Pardon?\n"
    .string "Tu n'as pas ¥5000?\p"
    .string "Décidemment tu ne peux pas\n"
    .string "rejoindre notre concours!\p"
    .string "Reviens plus tard avec de\n"
    .string "l'argent et je t'apprendais PLAQUAGE.$"

FourIsland_PokemonCenter_1F_Text_RareIceMonsInCave::
    .string "Il y a un POKéMON GLACE très\n"
    .string "rare qui vit dans cette grotte.\p"
    .string "Y'a plein de monde qui vient ici\n"
    .string "en espérant le voir.$"

FourIsland_PokemonCenter_1F_Text_DayCarePeopleFoundEggBefore::
    .string "Oh? Un OEUF POKéMON?\n"
    .string "…Aucune idée.\p"
    .string "Oh, attends, il me semble que les\n"
    .string "gens de la PENSION en parlaient.\p"
    .string "Ils disaient en avoir déjà eu\n"
    .string "chez eux.$"

FourIsland_PokemonCenter_1F_Text_NewPokemonJournalHasntArrived::
    .string "Quoi?\p"
    .string "Le nouveau JOURNAL POKéMON\n"
    .string "n'est pas encore arrivé sur l'île?$"

