name: Build ROM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential binutils-arm-none-eabi git libpng-dev

      - name: Build agbcc
        run: |
          git clone https://github.com/pret/agbcc
          cd agbcc
          ./build.sh
          ./install.sh ../

      - name: Build ROM
        run: make

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: RFVF-Plus
          path: pokefirered.gba          make -j${nproc} all

      - name: Move symfiles
        if: ${{ github.event_name == 'push' }}
        run: |
          cp *.sym symbols/
          echo "SYMBOLS_COMMIT_MSG=$( git log --format=%s ${GITHUB_SHA} )" >> $GITHUB_ENV

      - name: Update symfiles
        if: ${{ github.event_name == 'push' }}
        uses: EndBug/add-and-commit@v7
        with:
          branch: symbols
          cwd: "./symbols"
          add: "*.sym"
          message: ${{ env.SYMBOLS_COMMIT_MSG }}
