PalletTown_Text_OakDontGoOut::
    .string "CHEN: Hé, attends!\n"
    .string "Ne pars pas!$"

PalletTown_Text_OakGrassUnsafeNeedMon::
    .string "CHEN: C'est très dangereux!\n"
    .string "Des POKéMON sauvages infestent\l"
    .string "les hautes herbes!\p"
    .string "Il te faut un POKéMON pour te\n"
    .string "protéger… Je sais!\p"
    .string "Suis-moi!$"

PalletTown_Text_RaisingMonsToo::
    .string "J'élève des POKéMON, moi aussi!\p"
    .string "Une fois forts, ils pourront me\n"
    .string "protéger!$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
    .string "Le progrès… C'est dément!\p"
    .string "On peut désormais stocker et même\n"
    .string "retirer des objets ou des\l"
    .string "POKéMON via un PC!$"

PalletTown_Text_OakPokemonResearchLab::
    .string "LABO POKéMON DU PROF. CHEN$"

PalletTown_Text_PlayersHouse::
    .string "Maison de {PLAYER}$"

PalletTown_Text_RivalsHouse::
    .string "Maison de {RIVAL}$"

PalletTown_Text_TownSign::
    .string "BOURG PALETTE\n"
    .string "Un monde de couleurs\l"
    .string "s'ouvre à vous!$"

PalletTown_Text_OakLetMeSeePokedex::
    .string "CHEN: Je suis content de te\n"
    .string "revoir. Où en es-tu avec ton\l"
    .string "POKéDEX?\p"
    .string "Voyons, voyons…$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
    .string "Tu en a attrapé {STR_VAR_2}…\p"
    .string "Hm, on dirait que tu y met\n"
    .string "beaucoup de volonté.\p"
    .string "Il y a quelque chose que je\n"
    .string "voulais te demander, {PLAYER}.\p"
    .string "Viens.\n"
    .string "Suis moi.$"

PalletTown_Text_CaughtXImpressiveFollowMe::
    .string "Tu en a attrapé… {STR_VAR_2}?!\p"
    .string "C'est impressionnant!\p"
    .string "Il y a quelque chose que je voulais\n"
    .string "te demander, {PLAYER}.\p"
    .string "Viens.\n"
    .string "Suis moi.$"

PalletTown_Text_OakYouEnjoyingTraveling::
    .string "CHEN: Ah, {PLAYER}!\n"
    .string "On dirait que tu aimes voyager.\p"
    .string "Te connaissant, {PLAYER}, je peux\n"
    .string "imaginer que tu te diriges vers\l"
    .string "des endroits encore plus exotiques.\p"
    .string "Je suis heureux pour toi.\n"
    .string "Hohoho.$"

